# -*- coding: utf-8 -*-
ASILAH_ES = [
 ("<title>Asilah: The Artists' Town on the Atlantic | Abrid Morocco</title>", "<title>Asilah: la ciudad de los artistas en el Atlántico | Abrid Morocco</title>"),
 ('content="Asilah guide: whitewashed medina, Portuguese ramparts, festival murals and Atlantic beaches south of Tangier. Visit with Abrid Morocco."', 'content="Guía de Asilah: medina encalada, murallas portuguesas, murales del festival y playas atlánticas al sur de Tánger. Visita con Abrid Morocco."'),
 ('content="Asilah: The Artists\' Town on the Atlantic | Abrid Morocco"', 'content="Asilah: la ciudad de los artistas en el Atlántico | Abrid Morocco"'),
 ('content="Whitewashed lanes, painted murals and ocean ramparts — a slow Atlantic stop south of Tangier."', 'content="Callejones encalados, murales pintados y murallas frente al océano: una tranquila parada atlántica al sur de Tánger."'),
 ('content="Asilah: The Artists\' Town on the Atlantic"', 'content="Asilah: la ciudad de los artistas en el Atlántico"'),
 ('content="Murals, medina and Atlantic beaches — visiting Asilah."', 'content="Murales, medina y playas atlánticas: visitar Asilah."'),
 ('"name":"Asilah","description":"Atlantic coastal town south of Tangier with a whitewashed medina, Portuguese ramparts and an annual arts festival."', '"name":"Asilah","description":"Ciudad costera atlántica al sur de Tánger con medina encalada, murallas portuguesas y un festival anual de arte."'),
 ('"name":"Asilah","item":"https://www.abridmorocco.com/es/destination-asilah.html"', '"name":"Asilah","item":"https://www.abridmorocco.com/es/destination-asilah.html"'),
 ('"name":"Home","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinations"', '"name":"Inicio","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinos"'),
 ('<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="https://www.abridmorocco.com/index.html">Home</a><span>/</span><a href="https://www.abridmorocco.com/destinations.html">Destinations</a><span>/</span><span>Asilah</span></nav>',
  '<nav class="breadcrumbs" aria-label="Migas de pan"><a href="https://www.abridmorocco.com/index.html">Inicio</a><span>/</span><a href="https://www.abridmorocco.com/destinations.html">Destinos</a><span>/</span><span>Asilah</span></nav>'),
 ('aria-label="Breadcrumb"', 'aria-label="Migas de pan"'),
 ('<span class="eyebrow">Destination · North Morocco</span>', '<span class="eyebrow">Destino · Norte de Marruecos</span>'),
 ('<h1>Asilah: <span class="highlight">The Artists\' Town</span></h1>', '<h1>Asilah: <span class="highlight">la ciudad de los artistas</span></h1>'),
 ("<p>Whitewashed lanes, painted murals and Portuguese ramparts over the Atlantic — Asilah is the north's slowest, gentlest stop.</p>",
  "<p>Callejones encalados, murales pintados y murallas portuguesas sobre el Atlántico: Asilah es la parada más tranquila y suave del norte.</p>"),
 ("<span class=\"meta-item\">🎨 Festival murals</span>", "<span class=\"meta-item\">🎨 Murales del festival</span>"),
 ("<span class=\"meta-item\">🏰 Portuguese ramparts</span>", "<span class=\"meta-item\">🏰 Murallas portuguesas</span>"),
 ("<span class=\"meta-item\">🏖️ Atlantic beaches</span>", "<span class=\"meta-item\">🏖️ Playas atlánticas</span>"),
 ("<span class=\"meta-item\">🚂 Rail from Tangier</span>", "<span class=\"meta-item\">🚂 Tren desde Tánger</span>"),
 ('alt="Ramparts and boats on Morocco\'s Atlantic coast"', 'alt="Murallas y barcos en la costa atlántica de Marruecos"'),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Murals, medina, ocean</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Murales, medina, océano</h2>'),
 ("Every year the town's cultural festival invites artists to repaint the medina walls, so Asilah's lanes are an open-air gallery that changes with the seasons. Behind Portuguese-era ramparts you find a compact whitewashed medina, a small fishing port and long sandy beaches — including the well-known Paradise Beach just south of town.",
  "Cada año el festival cultural invita a artistas a repintar los muros de la medina: los callejones de Asilah son una galería al aire libre que cambia con las estaciones. Tras las murallas portuguesas hay una medina compacta encalada, un pequeño puerto pesquero y largas playas de arena, incluida la conocida playa Paradise al sur."),
 ("Asilah suits travellers moving between", "Asilah conviene a quienes viajan entre"),
 ("who want one slow coastal pause. Half a day covers the medina and ramparts; stay for sunset and the town earns its reputation.",
  "y quieren una tranquila pausa costera. Medio día cubre la medina y las murallas; quédate al atardecer y la ciudad se ganará su fama."),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Highlights</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Lo más destacado</h2>'),
 ("<li><strong>Medina murals</strong> — repainted festival artworks on whitewashed walls.</li>", "<li><strong>Murales de la medina</strong> — obras del festival repintadas sobre muros encalados.</li>"),
 ("<li><strong>Portuguese ramparts</strong> — sea walls and the old El-Kamra tower.</li>", "<li><strong>Murallas portuguesas</strong> — murallas marinas y la vieja torre El-Kamra.</li>"),
 ("<li><strong>Fishing port</strong> — watch the afternoon boats come in.</li>", "<li><strong>Puerto pesquero</strong> — mira llegar los barcos por la tarde.</li>"),
 ("<li><strong>Paradise Beach</strong> — long sand south of town.</li>", "<li><strong>Playa Paradise</strong> — larga arena al sur de la ciudad.</li>"),
 ("<li><strong>Sunset on the ramparts</strong> — Asilah's essential evening hour.</li>", "<li><strong>Atardecer en las murallas</strong> — la hora esencial de Asilah.</li>"),
 ("<strong>How we recommend experiencing Asilah.</strong> Morning in the medina before the day-trippers, grilled fish lunch at the port, beach afternoon, sunset on the walls. <strong>How long:</strong> half a day to one night. <strong>What travellers miss:</strong> the murals change yearly — ask a local which walls are new. <strong>How we connect it:</strong> Tangier → Asilah → Rabat is the natural Atlantic drive south.",
  "<strong>Cómo recomendamos vivir Asilah.</strong> Mañana en la medina antes de los excursionistas, almuerzo de pescado a la brasa en el puerto, tarde de playa y atardecer en las murallas. <strong>Duración:</strong> de medio día a una noche. <strong>Lo que se pierde el viajero:</strong> los murales cambian cada año; pregunta a un local qué muros son nuevos. <strong>Nuestra conexión:</strong> Tánger → Asilah → Rabat es la ruta atlántica natural hacia el sur."),
 ('<h3 style="font-weight:500;font-size:1.1rem;margin:0 0 6px;">How to get there</h3>', '<h3 style="font-weight:500;font-size:1.1rem;margin:0 0 6px;">Cómo llegar</h3>'),
 ("Asilah sits on the Tangier–Casablanca rail line, so trains from Tangier and Rabat stop here; by road it is roughly an hour south of Tangier. With Abrid, the stop is simply folded into your Atlantic route.",
  "Asilah está en la línea férrea Tánger–Casablanca: paran los trenes de Tánger y Rabat; por carretera es una hora al sur de Tánger. Con Abrid, la parada se integra sin más en tu ruta atlántica."),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Good to know</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Conviene saber</h2>'),
 ('<h3 style="font-weight:500;font-size:1.1rem;margin:18px 0 6px;">How long to stay</h3>', '<h3 style="font-weight:500;font-size:1.1rem;margin:18px 0 6px;">Cuánto tiempo quedarse</h3>'),
 ("We recommend half a day for the medina and ramparts, or one night to catch sunset and the beach. Few travellers need longer.",
  "Recomendamos medio día para la medina y las murallas, o una noche para el atardecer y la playa. Pocos viajeros necesitan más."),
 ('<h3 style="font-weight:500;font-size:1.1rem;margin:18px 0 6px;">Best time to visit</h3>', '<h3 style="font-weight:500;font-size:1.1rem;margin:18px 0 6px;">Mejor época</h3>'),
 ("Spring (March–May) and autumn (September–November) are generally ideal; summer brings beach weather and the cultural festival season.",
  "La primavera (marzo–mayo) y el otoño (septiembre–noviembre) suelen ser ideales; el verano trae tiempo de playa y la temporada del festival cultural."),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:6px;">Best areas to visit in Asilah</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:6px;">Mejores zonas que visitar en Asilah</h2>'),
 ("<p style=\"color:var(--text-muted);margin-bottom:14px;\">Compact town, three zones — medina, walls and sand.</p>", "<p style=\"color:var(--text-muted);margin-bottom:14px;\">Ciudad compacta, tres zonas: medina, murallas y arena.</p>"),
 ("<span class=\"discover-src\">MEDINA</span><h4>Murals &amp; lanes</h4><p>Repainted festival artworks on whitewashed walls around every corner.</p>",
  "<span class=\"discover-src\">MEDINA</span><h4>Murales y callejones</h4><p>Obras del festival repintadas sobre muros encalados en cada esquina.</p>"),
 ("<span class=\"discover-src\">RAMPARTS</span><h4>Walls &amp; tower</h4><p>Sea walls, El-Kamra tower and the sunset walk above the ocean.</p>",
  "<span class=\"discover-src\">MURALLAS</span><h4>Muros y torre</h4><p>Murallas marinas, torre El-Kamra y paseo al atardecer sobre el océano.</p>"),
 ("<span class=\"discover-src\">BEACH</span><h4>Paradise Beach</h4><p>Long sand south of town for swimming and slow afternoons.</p>",
  "<span class=\"discover-src\">PLAYA</span><h4>Playa Paradise</h4><p>Larga arena al sur para nadar y tardes tranquilas.</p>"),
 ('aria-label="Map of Asilah areas"', 'aria-label="Mapa de las zonas de Asilah"'),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Trips visiting Asilah</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Viajes que pasan por Asilah</h2>'),
 ("<div class=\"dest-tour\"><h3>Private Custom Trips</h3><p>Atlantic Morocco built around you — Asilah, Rabat, Casablanca and the coast.</p>", "<div class=\"dest-tour\"><h3>Viajes privados a medida</h3><p>El Marruecos atlántico a tu medida: Asilah, Rabat, Casablanca y la costa.</p>"),
 ('>View tour</a>', '>Ver el tour</a>'),
 ("No fixed Asilah trip yet?", "¿Aún no hay viaje fijo a Asilah?"),
 ("and we add it to a coastal route.", "y lo añadiremos a una ruta costera."),
 ('>Tell us your dates</a>', '>Dinos tus fechas</a>'),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Morocco guides</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Guías de Marruecos</h2>'),
 ("<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-destinations.html\"><h3>Destinations Guide</h3><p>Marrakech to Chefchaouen →</p></a>", "<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-destinations.html\"><h3>Guía de destinos</h3><p>De Marrakech a Chauen →</p></a>"),
 ("<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-best-time.html\"><h3>Best Time to Visit</h3><p>Seasons by region →</p></a>", "<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-best-time.html\"><h3>Mejor época</h3><p>Estaciones por región →</p></a>"),
 ("<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-transport.html\"><h3>Transport Guide</h3><p>Trains, buses &amp; cars →</p></a>", "<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-transport.html\"><h3>Guía de transporte</h3><p>Trenes, autobuses y coches →</p></a>"),
 ("<h3>Tangier Guide</h3><p>The northern door →</p>", "<h3>Guía de Tánger</h3><p>La puerta del norte →</p>"),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Asilah questions</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Preguntas sobre Asilah</h2>'),
 ("<summary>Is Asilah worth a stop?</summary><p>Yes as a half-day coastal pause between Tangier and Rabat — the murals, ramparts and sunset are the draw. It is a restful town rather than a full-day destination.</p>",
  "<summary>¿Merece la pena parar en Asilah?</summary><p>Sí como pausa costera de medio día entre Tánger y Rabat: los murales, las murallas y el atardecer son el atractivo. Es una ciudad de descanso más que un destino de día entero.</p>"),
 ("<summary>When is the arts festival?</summary><p>The cultural moussem usually runs in summer, when new murals are painted. Dates shift yearly — ask us when planning and we will check what is on.</p>",
  "<summary>¿Cuándo es el festival de arte?</summary><p>El musem cultural suele celebrarse en verano, cuando se pintan los nuevos murales. Las fechas cambian cada año: pregúntanos al planificar y comprobamos el programa.</p>"),
 ("<summary>Can Abrid include Asilah in my trip?</summary><p>Easily — it slots into any Tangier-to-Rabat coastal drive.", "<summary>¿Puede Abrid incluir Asilah en mi viaje?</summary><p>Fácilmente: encaja en cualquier ruta costera de Tánger a Rabat."),
 ('>Request it here</a>.', '>Pídelo aquí</a>.'),
 ("<h2>Asilah in photos</h2>", "<h2>Asilah en fotos</h2>"),
 ("<p>Real shots from our routes around Asilah. All photos from the Abrid Morocco local library.</p>", "<p>Fotos reales de nuestras rutas por Asilah. Todas las fotos son de la biblioteca local de Abrid Morocco.</p>"),
 ('alt="Asilah festival murals whitewashed medina lanes Morocco"', 'alt="Murales del festival y callejones encalados de Asilah, Marruecos"'),
 ('alt="Portuguese ramparts El-Kamra tower Asilah Atlantic Morocco"', 'alt="Murallas portuguesas y torre El-Kamra en Asilah, Atlántico, Marruecos"'),
 ('alt="Asilah fishing port afternoon boats Morocco"', 'alt="Barcos de tarde en el puerto pesquero de Asilah, Marruecos"'),
 ('alt="Paradise Beach long sand south of Asilah Morocco"', 'alt="Larga arena de playa Paradise al sur de Asilah, Marruecos"'),
 ('alt="Sunset walk on Asilah sea walls Morocco"', 'alt="Paseo al atardecer por las murallas marinas de Asilah, Marruecos"'),
 ("<h2>Want to include Asilah in your Morocco trip?</h2>", "<h2>¿Quieres incluir Asilah en tu viaje a Marruecos?</h2>"),
 ("<p>Tell us your dates and interests — we fold Asilah into an Atlantic route with transport, stays and guides handled.</p>", "<p>Dinos tus fechas e intereses: integramos Asilah en una ruta atlántica con transporte, alojamientos y guías incluidos.</p>"),
 ('>Plan My Morocco Trip</a>', '>Planifica mi viaje a Marruecos</a>'),
 ('>Explore Trips</a>', '>Explorar viajes</a>'),
 ('<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Abrid Morocco logo"', '<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Logotipo de Abrid Morocco"'),
]

CHEF_ES = [
 ("<title>Chefchaouen Travel Guide &amp; Tours | Abrid Morocco</title>", "<title>Guía de viaje y tours de Chauen | Abrid Morocco</title>"),
 ('content="Chefchaouen destination guide: the blue Pearl of the Rif - the medina, the Spanish Mosque viewpoint, Akchour falls, and how to include it in a Morocco route."', 'content="Guía de Chauen: la Perla azul del Rif — la medina, el mirador de la Mezquita Española, las cascadas de Akchour y cómo incluirla en una ruta por Marruecos."'),
 ('content="Chefchaouen Travel Guide &amp; Tours | Abrid Morocco"', 'content="Guía de viaje y tours de Chauen | Abrid Morocco"'),
 ('content="Chefchaouen destination guide: the blue Pearl of the Rif &mdash; the medina, the Spanish Mosque viewpoint, Akchour falls and how to include it in a Morocco route."', 'content="Guía de Chauen: la Perla azul del Rif — la medina, el mirador de la Mezquita Española, las cascadas de Akchour y cómo incluirla en una ruta por Marruecos."'),
 ('"description": "Chefchaouen destination guide: the blue Pearl of the Rif &mdash; the medina, the Spanish Mosque viewpoint, Akchour falls and how to include it in a Morocco route."', '"description": "Guía de Chauen: la Perla azul del Rif — la medina, el mirador de la Mezquita Española, las cascadas de Akchour y cómo incluirla en una ruta por Marruecos."'),
 ('"name": "How long should I stay?"', '"name": "¿Cuánto tiempo quedarse?"'),
 ('"text": "One full day for the medina and viewpoint, plus a half-day for Akchour if you enjoy walking. Many travellers stay two nights."', '"text": "Un día entero para la medina y el mirador, más medio día para Akchour si te gusta caminar. Muchos viajeros se quedan dos noches."'),
 ('"name": "Is Chefchaouen on the way anywhere?"', '"name": "¿Chauen queda de paso?"'),
 ('"text": "It works best on a northern route linking Tangier, Fes and the Imperial Cities — which is how our classic circuits include it."', '"text": "Se disfruta mejor en una ruta del norte que une Tánger, Fez y las Ciudades Imperiales; así la incluyen nuestros circuitos clásicos."'),
 ('"name": "Why is the town painted blue?"', '"name": "¿Por qué la ciudad está pintada de azul?"'),
 ('"text": "Tradition links it to a Jewish community that settled here, and the blue is said to repel mosquitoes and keep homes cool — whatever the reason, the effect is magical."', '"text": "La tradición lo vincula a una comunidad judía instalada aquí, y se dice que el azul ahuyenta los mosquitos y mantiene frescas las casas; sea cual sea la razón, el efecto es mágico."'),
 ('"name":"Chefchaouen","item":"https://www.abridmorocco.com/es/destination-chefchaouen.html"', '"name":"Chauen","item":"https://www.abridmorocco.com/es/destination-chefchaouen.html"'),
 ('"name":"Home","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinations"', '"name":"Inicio","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinos"'),
 ('<span class="eyebrow">Abrid Morocco Destination</span>', '<span class="eyebrow">Destino Abrid Morocco</span>'),
 ('<p class="lead">Every shade of blue on a mountainside &mdash; Morocco&rsquo;s prettiest medina in the Rif, best seen at sunset from the Spanish Mosque.</p>',
  '<p class="lead">Todos los tonos de azul en una ladera — la medina más bonita de Marruecos en el Rif, mejor al atardecer desde la Mezquita Española.</p>'),
 ('>Marrakech <span class="arrow">', '>Marrakech <span class="arrow">'),
 ('>Sahara Desert <span class="arrow">', '>Desierto del Sáhara <span class="arrow">'),
 ('>Fes <span class="arrow">', '>Fez <span class="arrow">'),
 ('>Chefchaouen <span class="arrow">', '>Chauen <span class="arrow">'),
 ('>Essaouira <span class="arrow">', '>Esauira <span class="arrow">'),
 ('>Atlas Mountains <span class="arrow">', '>Montañas del Atlas <span class="arrow">'),
 ('>Ait Benhaddou <span class="arrow">', '>Ait Benhaddou <span class="arrow">'),
 ('>Agadir <span class="arrow">', '>Agadir <span class="arrow">'),
 ('<h2 style="font-weight:400;font-size:clamp(1.6rem,3vw,2.2rem);margin:0 0 8px">Chefchaouen &ndash; The Blue Pearl of the Rif</h2>', '<h2 style="font-weight:400;font-size:clamp(1.6rem,3vw,2.2rem);margin:0 0 8px">Chauen – la Perla Azul del Rif</h2>'),
 ("<p style=\"font-family:var(--font-body);color:var(--text-muted);max-width:720px;margin:0 0 28px\">A mountain town painted in every shade of blue, tucked into the Rif Mountains behind the cedar forests of the north.</p>",
  "<p style=\"font-family:var(--font-body);color:var(--text-muted);max-width:720px;margin:0 0 28px\">Una ciudad de montaña pintada en todos los tonos de azul, enclavada en el Rif tras los bosques de cedros del norte.</p>"),
 ('<span class="fact-label">Region</span><span class="fact-value">Rif Mountains, north-west Morocco</span>', '<span class="fact-label">Región</span><span class="fact-value">Montañas del Rif, noroeste de Marruecos</span>'),
 ('<span class="fact-label">Best time</span><span class="fact-value">Apr&ndash;Oct; Akshar in early summer</span>', '<span class="fact-label">Mejor época</span><span class="fact-value">Abr–oct; Akchour a principios de verano</span>'),
 ('<span class="fact-label">Icon</span><span class="fact-value">The blue-washed medina</span>', '<span class="fact-label">Icono</span><span class="fact-value">La medina teñida de azul</span>'),
 ('<span class="fact-label">Star view</span><span class="fact-value">Spanish Mosque viewpoint at sunset</span>', '<span class="fact-label">Mirador</span><span class="fact-value">Mezquita Española al atardecer</span>'),
 ("<p><strong>Chefchaouen</strong> climbs a mountainside beneath the peaks of Jebel el-Kala&rsquo;a. Its medina is famous the world over for walls and stairways washed in blues &mdash; calm, photogenic and perfectly walkable in a relaxed day or two.</p>",
  "<p><strong>Chauen</strong> sube por una ladera bajo los picos del Jebel el-Kalaa. Su medina es famosa en todo el mundo por muros y escaleras teñidos de azul: tranquila, fotogénica y perfecta a pie en uno o dos días relajados.</p>"),
 ("Start in the main square <strong>Plaza Uta el-Hammam</strong> with a mint tea and a view of the <strong>Grand Mosque</strong>, wander the artisan lanes of the <strong>kasbah</strong>, then hike a short way to the <strong>Spanish Mosque</strong> for the famous panorama as the town glows blue at sunset. The <strong>Akchour waterfalls</strong> and cedar forests of the Talassemtane National Park sit a short drive away.",
  "Empieza en la plaza principal <strong>Uta el-Hammam</strong> con un té a la menta y vistas a la <strong>Gran Mezquita</strong>, pasea por los callejones artesanos de la <strong>kasbah</strong> y sube un poco hasta la <strong>Mezquita Española</strong> para el famoso panorama cuando la ciudad brilla azul al atardecer. Las <strong>cascadas de Akchour</strong> y los cedros del Parque Nacional de Talassemtane están a un corto trayecto."),
 ("&ldquo;Chefchaouen is the place where travellers arrive for one night and quietly extend their stay for three.&rdquo; &mdash; Karim, guide",
  "«Chauen es el lugar donde los viajeros llegan para una noche y alargan en silencio su estancia a tres.» — Karim, guía"),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Highlights</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Lo más destacado</h3>'),
 ("<div class=\"dest-highlight\"><h3>The Blue Medina</h3><p>Winding alleys, painted doors and stairways &mdash; plan extra battery for photos.</p></div>",
  "<div class=\"dest-highlight\"><h3>La medina azul</h3><p>Callejones sinuosos, puertas pintadas y escaleras; lleva batería extra para fotos.</p></div>"),
 ("<div class=\"dest-highlight\"><h3>Spanish Mosque Viewpoint</h3><p>A short uphill walk to the classic sunset panorama over the whole town.</p></div>",
  "<div class=\"dest-highlight\"><h3>Mirador de la Mezquita Española</h3><p>Corta subida al clásico panorama al atardecer sobre toda la ciudad.</p></div>"),
 ("<div class=\"dest-highlight\"><h3>Kasbah & Souk</h3><p>A 15th-century fortress, artisan crafts and a relaxed, unhurried market.</p></div>",
  "<div class=\"dest-highlight\"><h3>Kasbah y zoco</h3><p>Fortaleza del siglo XV, artesanía y un mercado relajado sin prisas.</p></div>"),
 ("<div class=\"dest-highlight\"><h3>Akchour Waterfalls</h3><p>Gorges, natural bridges and pine-shaded river trails an hour from the town.</p></div>",
  "<div class=\"dest-highlight\"><h3>Cascadas de Akchour</h3><p>Gargantas, puentes naturales y senderos de pinos a una hora de la ciudad.</p></div>"),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 8px">Best areas to visit in Chefchaouen</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 8px">Mejores zonas que visitar en Chauen</h3>'),
 ("<p style=\"color:var(--text-muted);margin-bottom:14px;\">Medina blue, hilltop views and waterfall valleys beyond.</p>", "<p style=\"color:var(--text-muted);margin-bottom:14px;\">Azul de la medina, vistas desde las colinas y valles de cascadas más allá.</p>"),
 ("<span class=\"discover-src\">MEDINA</span><h4>Blue lanes</h4><p>Painted doors, stairways and the Uta el-Hammam square.</p>",
  "<span class=\"discover-src\">MEDINA</span><h4>Callejones azules</h4><p>Puertas pintadas, escaleras y la plaza Uta el-Hammam.</p>"),
 ("<span class=\"discover-src\">VIEWPOINT</span><h4>Spanish Mosque hill</h4><p>Sunset panorama over the whole blue town.</p>",
  "<span class=\"discover-src\">MIRADOR</span><h4>Colina de la Mezquita Española</h4><p>Panorama al atardecer sobre toda la ciudad azul.</p>"),
 ("<span class=\"discover-src\">VALLEY</span><h4>Ras El-Maa &amp; Akchour</h4><p>River springs at the medina edge, waterfalls further out.</p>",
  "<span class=\"discover-src\">VALLE</span><h4>Ras El-Maa y Akchour</h4><p>Manantiales junto a la medina y cascadas más lejos.</p>"),
 ('aria-label="Map of Chefchaouen areas"', 'aria-label="Mapa de las zonas de Chauen"'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Chefchaouen in Pictures</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Chauen en imágenes</h3>'),
 ('alt="Blue Medina alley in Chefchaouen Morocco"', 'alt="Callejón de la medina azul de Chauen, Marruecos"'),
 ('>The Blue Medina from Above</figcaption>', '>La medina azul desde arriba</figcaption>'),
 ('alt="Blue Callejón El Asri alley in Chefchaouen"', 'alt="Callejón azul El Asri en Chauen, Marruecos"'),
 ('>Callejón El Asri Blue Alley</figcaption>', '>Callejón azul El Asri</figcaption>'),
 ('alt="Spanish Mosque overlooking Chefchaouen"', 'alt="Mezquita Española sobre Chauen, Marruecos"'),
 ('>Spanish Mosque Sunset View</figcaption>', '>Mezquita Española al atardecer</figcaption>'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Taste of Chefchaouen</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Sabores de Chauen</h3>'),
 ('alt="Rif goat cheese and olives from northern Morocco"', 'alt="Queso de cabra del Rif y aceitunas del norte de Marruecos"'),
 ('>Rif Goat Cheese & Olives</figcaption>', '>Queso de cabra del Rif y aceitunas</figcaption>'),
 ('alt="Moroccan mountain mint tea"', 'alt="Té a la menta de las montañas marroquíes"'),
 ('>Mountain Mint Tea</figcaption>', '>Té a la menta de montaña</figcaption>'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Trips that include Chefchaouen</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Viajes que incluyen Chauen</h3>'),
 ("<div class=\"dest-tour\"><h3>Classic 13-Day Morocco</h3><p>The full circuit lands in the blue town after Fes, before heading south.</p>", "<div class=\"dest-tour\"><h3>Marruecos clásico en 13 días</h3><p>El circuito completo llega a la ciudad azul tras Fez, antes de ir al sur.</p>"),
 ("<div class=\"dest-tour\"><h3>6-Day Christmas Journey</h3><p>Begins in Tangier via Chefchaouen and the cedar forests on the way to the desert.</p>", "<div class=\"dest-tour\"><h3>Viaje de Navidad en 6 días</h3><p>Empieza en Tánger vía Chauen y los cedros camino del desierto.</p>"),
 ("<div class=\"dest-tour\"><h3>Private Custom Trips</h3><p>Add Chefchaouen and the Rif to your own northern route.</p>", "<div class=\"dest-tour\"><h3>Viajes privados a medida</h3><p>Añade Chauen y el Rif a tu propia ruta del norte.</p>"),
 ('>View tour</a>', '>Ver el tour</a>'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Good to know</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Conviene saber</h3>'),
 ("<h2>Chefchaouen in photos</h2>", "<h2>Chauen en fotos</h2>"),
 ("<p>Real shots from our routes around Chefchaouen. All photos from the Abrid Morocco local library.</p>", "<p>Fotos reales de nuestras rutas por Chauen. Todas las fotos son de la biblioteca local de Abrid Morocco.</p>"),
 ('alt="Chefchaouen blue medina alley stairs Rif Morocco"', 'alt="Escaleras de la medina azul de Chauen, Rif, Marruecos"'),
 ('alt="Plaza Uta el-Hammam Grand Mosque Chefchaouen Morocco"', 'alt="Plaza Uta el-Hammam y Gran Mezquita de Chauen, Marruecos"'),
 ('alt="Spanish Mosque sunset panorama over Chefchaouen Morocco"', 'alt="Panorama al atardecer desde la Mezquita Española sobre Chauen, Marruecos"'),
 ('alt="Akchour waterfalls trails near Chefchaouen Morocco"', 'alt="Senderos de las cascadas de Akchour cerca de Chauen, Marruecos"'),
 ('<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Abrid Morocco logo"', '<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Logotipo de Abrid Morocco"'),
]

MARRA_ES = [
 ("<title>Marrakech Travel Guide &amp; Tours | Abrid Morocco</title>", "<title>Guía de viaje y tours de Marrakech | Abrid Morocco</title>"),
 ('content="Marrakech destination guide: the Red City, its souks, palaces and gardens - plus the best day trips into the High Atlas and Sahara."', 'content="Guía de Marrakech: la Ciudad Roja, sus zocos, palacios y jardines, más las mejores excursiones al Alto Atlas y al Sáhara."'),
 ('content="Marrakech Travel Guide &amp; Tours | Abrid Morocco"', 'content="Guía de viaje y tours de Marrakech | Abrid Morocco"'),
 ('content="Marrakech destination guide: the Red City, its souks, palaces, gardens and the best day trips into the High Atlas and Sahara &mdash; with local Abrid Morocco guides."', 'content="Guía de Marrakech: la Ciudad Roja, sus zocos, palacios, jardines y las mejores excursiones al Alto Atlas y al Sáhara, con guías locales de Abrid Morocco."'),
 ('"description": "Marrakech destination guide: the Red City, its souks, palaces, gardens and the best day trips into the High Atlas and Sahara &mdash; with local Abrid Morocco guides."', '"description": "Guía de Marrakech: la Ciudad Roja, sus zocos, palacios, jardines y las mejores excursiones al Alto Atlas y al Sáhara, con guías locales de Abrid Morocco."'),
 ('"name": "How many days should I spend in Marrakech?"', '"name": "¿Cuántos días pasar en Marrakech?"'),
 ('"text": "Two full days lets you cover the medina at a relaxed pace and still keep time for a rooftop meal or a day trip into the Atlas."', '"text": "Dos días enteros permiten cubrir la medina a ritmo relajado y aún guardar tiempo para una comida en una terraza o una excursión al Atlas."'),
 ('"name": "Is Marrakech safe for visitors?"', '"name": "¿Es seguro Marrakech para los visitantes?"'),
 ('"text": "Yes. Usual city awareness applies — agree taxi fares before setting off and ignore persistent street touts. Your guide handles all the logistics for you."', '"text": "Sí. Aplica la precaución urbana habitual: acuerda la tarifa del taxi antes de salir e ignora a los vendedores insistentes. Tu guía se encarga de toda la logística."'),
 ('"name": "Which trips start from Marrakech?"', '"name": "¿Qué viajes salen de Marrakech?"'),
 ('"text": "Most of our routes do: Sahara desert tours, Atlas day trips, Essaouira, Ouzoud waterfalls and all multi-day circuits."', '"text": "La mayoría de nuestras rutas: tours al desierto del Sáhara, excursiones al Atlas, Esauira, cascadas de Ouzoud y todos los circuitos de varios días."'),
 ('"name":"Marrakech","item":"https://www.abridmorocco.com/es/destination-marrakech.html"', '"name":"Marrakech","item":"https://www.abridmorocco.com/es/destination-marrakech.html"'),
 ('"name":"Home","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinations"', '"name":"Inicio","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinos"'),
 ('<span class="eyebrow">Abrid Morocco Destination</span>', '<span class="eyebrow">Destino Abrid Morocco</span>'),
 ('<p class="lead">The Red City &mdash; gateway to the Sahara, the Atlas and the coast. Where Morocco begins for most travellers, guided by people who call it home.</p>',
  '<p class="lead">La Ciudad Roja: puerta al Sáhara, al Atlas y a la costa. Donde empieza Marruecos para la mayoría, guiados por quienes la llaman hogar.</p>'),
 ('>Marrakech <span class="arrow">', '>Marrakech <span class="arrow">'),
 ('>Sahara Desert <span class="arrow">', '>Desierto del Sáhara <span class="arrow">'),
 ('>Fes <span class="arrow">', '>Fez <span class="arrow">'),
 ('>Chefchaouen <span class="arrow">', '>Chauen <span class="arrow">'),
 ('>Essaouira <span class="arrow">', '>Esauira <span class="arrow">'),
 ('>Atlas Mountains <span class="arrow">', '>Montañas del Atlas <span class="arrow">'),
 ('>Ait Benhaddou <span class="arrow">', '>Ait Benhaddou <span class="arrow">'),
 ('>Agadir <span class="arrow">', '>Agadir <span class="arrow">'),
 ('<h2 style="font-weight:400;font-size:clamp(1.6rem,3vw,2.2rem);margin:0 0 8px">The Red City &ndash; Marrakech</h2>', '<h2 style="font-weight:400;font-size:clamp(1.6rem,3vw,2.2rem);margin:0 0 8px">La Ciudad Roja: Marrakech</h2>'),
 ("<p style=\"font-family:var(--font-body);color:var(--text-muted);max-width:720px;margin:0 0 28px\">Palace courtyards, maze-like souks, rooftop views over Jemaa el-Fnaa and easy access to the High Atlas. Marrakech is where most Morocco journeys begin.</p>",
  "<p style=\"font-family:var(--font-body);color:var(--text-muted);max-width:720px;margin:0 0 28px\">Patios de palacios, zocos laberínticos, vistas desde terrazas sobre Jemaa el-Fna y fácil acceso al Alto Atlas. Marrakech es donde empiezan la mayoría de los viajes por Marruecos.</p>"),
 ('<span class="fact-label">Region</span><span class="fact-value">South-west, near the High Atlas</span>', '<span class="fact-label">Región</span><span class="fact-value">Suroeste, junto al Alto Atlas</span>'),
 ('<span class="fact-label">Best time</span><span class="fact-value">Mar&ndash;May &amp; Sep&ndash;Nov</span>', '<span class="fact-label">Mejor época</span><span class="fact-value">Mar–may y sep–nov</span>'),
 ('<span class="fact-label">Vibe</span><span class="fact-value">Historic city, markets, day-trip hub</span>', '<span class="fact-label">Ambiente</span><span class="fact-value">Ciudad histórica, mercados, base de excursiones</span>'),
 ('<span class="fact-label">Base for</span><span class="fact-value">Sahara, Atlas &amp; coast trips</span>', '<span class="fact-label">Base para</span><span class="fact-value">Sáhara, Atlas y costa</span>'),
 ("Marrakech is the gateway to southern Morocco. Around the UNESCO-listed medina you will find the 12th-century <strong>Koutoubia Mosque</strong>, the ornate <strong>Bahia Palace</strong>, the serene <strong>Majorelle Garden</strong> and the ever-moving theatre of <strong>Jemaa el-Fnaa</strong> &mdash; storytellers, musicians, food stalls and snake charmers at dusk.",
  "Marrakech es la puerta al sur de Marruecos. En torno a la medina UNESCO encontrarás la <strong>mezquita Kutubía</strong> del siglo XII, el ornamentado <strong>palacio Bahía</strong>, el sereno <strong>jardín Majorelle</strong> y el teatro siempre vivo de <strong>Jemaa el-Fna</strong>: cuentacuentos, músicos, puestos de comida y encantadores de serpientes al atardecer."),
 ("Beyond the walls, the same city is the launch point for the classic routes we run: desert experiences towards Merzouga, mountain days in the Ourika Valley, hot air balloon flights at sunrise, and a day at the Atlantic in Essaouira.",
  "Más allá de las murallas, la misma ciudad es el punto de partida de nuestras rutas clásicas: experiencias en el desierto hacia Merzouga, días de montaña en el valle de Ourika, vuelos en globo al amanecer y un día atlántico en Esauira."),
 ("&ldquo;Marrakech rewards slow mornings: mint tea on a rooftop, the call to prayer drifting over the medina, then a long lunch with a view.&rdquo; &mdash; Abdellah, founder &amp; Berber guide",
  "«Marrakech premia las mañanas lentas: té a la menta en una terraza, la llamada a la oración sobre la medina y luego un largo almuerzo con vistas.» — Abdellah, fundador y guía bereber"),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Highlights</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Lo más destacado</h3>'),
 ("<div class=\"dest-highlight\"><h3>Jemaa el-Fnaa</h3><p>The famous square &mdash; try it at sunset for food stalls, storytellers and music.</p></div>",
  "<div class=\"dest-highlight\"><h3>Jemaa el-Fna</h3><p>La famosa plaza: pruébala al atardecer con puestos de comida, cuentacuentos y música.</p></div>"),
 ("<div class=\"dest-highlight\"><h3>The Souks</h3><p>Endless lanes of leather, spices, carpets and lamps &mdash; go early and bargain kindly.</p></div>",
  "<div class=\"dest-highlight\"><h3>Los zocos</h3><p>Callejones infinitos de cuero, especias, alfombras y lámparas; ve temprano y regatea con amabilidad.</p></div>"),
 ("<div class=\"dest-highlight\"><h3>Palaces & Gardens</h3><p>Bahia Palace, El Badi and the Majorelle Garden for calm and colour.</p></div>",
  "<div class=\"dest-highlight\"><h3>Palacios y jardines</h3><p>Palacio Bahía, El Badi y el jardín Majorelle para calma y color.</p></div>"),
 ("<div class=\"dest-highlight\"><h3>Rooftop Culture</h3><p>Atlas views, mint tea and slow afternoons above the medina rooftops.</p></div>",
  "<div class=\"dest-highlight\"><h3>Cultura de terrazas</h3><p>Vistas al Atlas, té a la menta y tardes lentas sobre los tejados de la medina.</p></div>"),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 8px">Best areas to visit in Marrakech</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 8px">Mejores zonas que visitar en Marrakech</h3>'),
 ("<p style=\"color:var(--text-muted);margin-bottom:14px;\">Three worlds in one city — old medina, new town and palm belt.</p>", "<p style=\"color:var(--text-muted);margin-bottom:14px;\">Tres mundos en una ciudad: medina antigua, ciudad nueva y palmeral.</p>"),
 ("<span class=\"discover-src\">MEDINA</span><h4>Jemaa el-Fna &amp; souks</h4><p>Square, palaces and craft lanes of the old city.</p>",
  "<span class=\"discover-src\">MEDINA</span><h4>Jemaa el-Fna y zocos</h4><p>Plaza, palacios y callejones artesanos de la ciudad antigua.</p>"),
 ("<span class=\"discover-src\">NEW TOWN</span><h4>Guéliz</h4><p>Galleries, cafés and Majorelle Garden streets.</p>",
  "<span class=\"discover-src\">CIUDAD NUEVA</span><h4>Guéliz</h4><p>Galerías, cafés y calles del jardín Majorelle.</p>"),
 ("<span class=\"discover-src\">PALMS</span><h4>Palmeraie</h4><p>Palm estates, pools and sunset camel rides.</p>",
  "<span class=\"discover-src\">PALMERAS</span><h4>Palmeraie</h4><p>Fincas de palmeras, piscinas y paseos en camello al atardecer.</p>"),
 ('aria-label="Map of Marrakech areas"', 'aria-label="Mapa de las zonas de Marrakech"'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Marrakech in Pictures</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Marrakech en imágenes</h3>'),
 ('alt="Koutoubia Mosque in Marrakech at sunset"', 'alt="Mezquita Kutubía en Marrakech al atardecer, Marruecos"'),
 ('>Koutoubia Mosque at Sunset</figcaption>', '>Mezquita Kutubía al atardecer</figcaption>'),
 ('alt="Bahia Palace courtyard in Marrakech"', 'alt="Patio del palacio Bahía en Marrakech, Marruecos"'),
 ('>Bahia Palace Courtyard</figcaption>', '>Patio del palacio Bahía</figcaption>'),
 ('alt="Jemaa el-Fnaa square in Marrakech"', 'alt="Plaza Jemaa el-Fna en Marrakech, Marruecos"'),
 ('>Jemaa el-Fnaa at Dusk</figcaption>', '>Jemaa el-Fna al anochecer</figcaption>'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Taste of Marrakech</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Sabores de Marrakech</h3>'),
 ('alt="Moroccan lamb tagine with prunes and almonds"', 'alt="Tajín marroquí de cordero con ciruelas y almendras, Marruecos"'),
 ('>Lamb Tagine with Prunes & Almonds</figcaption>', '>Tajín de cordero con ciruelas y almendras</figcaption>'),
 ('alt="Traditional Tanjia Marrakchia from Marrakech"', 'alt="Tanjía marrakchí tradicional de Marrakech, Marruecos"'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Trips from Marrakech</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Viajes desde Marrakech</h3>'),
 ("<div class=\"dest-tour\"><h3>Marrakech Discovery Tour</h3><p>Palaces, souks and medina highlights in a private guided day.</p>", "<div class=\"dest-tour\"><h3>Tour Descubrimiento de Marrakech</h3><p>Palacios, zocos y lo mejor de la medina en un día privado guiado.</p>"),
 ("<div class=\"dest-tour\"><h3>Hot Air Balloon Sunrise</h3><p>Float over the Haouz plains at dawn, then a Berber breakfast.</p>", "<div class=\"dest-tour\"><h3>Amanecer en globo</h3><p>Sobrevuela las llanuras de Haouz al amanecer y desayuno bereber.</p>"),
 ("<div class=\"dest-tour\"><h3>Atlas &amp; Ourika Day Trip</h3><p>Berber villages, waterfall hikes and mountain views an hour away.</p>", "<div class=\"dest-tour\"><h3>Excursión al Atlas y Ourika</h3><p>Pueblos bereberes, rutas de cascadas y vistas a una hora.</p>"),
 ("<div class=\"dest-tour\"><h3>Essaouira Day Trip</h3><p>A breezy Atlantic medina, seafood and ramparts &mdash; a relaxed escape.</p>", "<div class=\"dest-tour\"><h3>Excursión a Esauira</h3><p>Medina atlántica con brisa, marisco y murallas: una escapada relajada.</p>"),
 ("<div class=\"dest-tour\"><h3>3-Day Sahara Desert</h3><p>The classic Merzouga route: Ait Benhaddou, Dades, Todra &amp; Erg Chebbi.</p>", "<div class=\"dest-tour\"><h3>Desierto del Sáhara en 3 días</h3><p>La clásica ruta de Merzouga: Ait Benhaddou, Dades, Todra y Erg Chebbi.</p>"),
 ("<div class=\"dest-tour\"><h3>Private Custom Trips</h3><p>Build your own multi-day journey across Morocco.</p>", "<div class=\"dest-tour\"><h3>Viajes privados a medida</h3><p>Crea tu propio viaje de varios días por Marruecos.</p>"),
 ('>View tour</a>', '>Ver el tour</a>'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Good to know</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Conviene saber</h3>'),
 ("<h2>Marrakech in photos</h2>", "<h2>Marrakech en fotos</h2>"),
 ("<p>Real shots from our routes around Marrakech. All photos from the Abrid Morocco local library.</p>", "<p>Fotos reales de nuestras rutas por Marrakech. Todas las fotos son de la biblioteca local de Abrid Morocco.</p>"),
 ('alt="Jemaa el-Fnaa square at dusk Marrakech Morocco"', 'alt="Plaza Jemaa el-Fna al anochecer en Marrakech, Marruecos"'),
 ('alt="Bahia Palace courtyard zellige Marrakech Morocco"', 'alt="Patio de alicatado del palacio Bahía en Marrakech, Marruecos"'),
 ('<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Abrid Morocco logo"', '<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Logotipo de Abrid Morocco"'),
]
