# -*- coding: utf-8 -*-
TANGIER_ES = [
 ("<title>Tangier: Gateway Between Two Continents | Abrid Morocco</title>", "<title>Tánger: puerta entre dos continentes | Abrid Morocco</title>"),
 ('content="Tangier guide: Hercules Caves, Cap Spartel, the kasbah and medina — arriving by ferry from Spain and continuing to Chefchaouen and Fes."', 'content="Guía de Tánger: cuevas de Hércules, cabo Espartel, kasbah y medina — llegada en ferry desde España y continuación a Chauen y Fez."'),
 ('content="Tangier: Gateway Between Two Continents | Abrid Morocco"', 'content="Tánger: puerta entre dos continentes | Abrid Morocco"'),
 ('content="Where the Atlantic meets the Mediterranean — caves, capes and kasbahs at Morocco\'s northern door."', 'content="Donde el Atlántico se encuentra con el Mediterráneo — cuevas, cabos y kasbahs en la puerta norte de Marruecos."'),
 ('content="Tangier: Gateway Between Two Continents"', 'content="Tánger: puerta entre dos continentes"'),
 ('content="Hercules Caves, Cap Spartel and the old kasbah — starting Morocco in Tangier."', 'content="Cuevas de Hércules, cabo Espartel y la vieja kasbah — empezar Marruecos en Tánger."'),
 ('"name":"Tangier","description":"Northern Moroccan port city where the Atlantic meets the Mediterranean, arrival point for ferries from Spain."', '"name":"Tánger","description":"Ciudad portuaria del norte de Marruecos donde el Atlántico se encuentra con el Mediterráneo, punto de llegada de los ferris desde España."'),
 ('"name":"Tangier","item":"https://www.abridmorocco.com/es/destination-tangier.html"', '"name":"Tánger","item":"https://www.abridmorocco.com/es/destination-tangier.html"'),
 ('"name":"Home","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinations"', '"name":"Inicio","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinos"'),
 ('<span class="eyebrow">Destination · The North</span>', '<span class="eyebrow">Destino · El norte</span>'),
 ('<h1>Tangier: <span class="highlight">Gateway Between Continents</span></h1>', '<h1>Tánger: <span class="highlight">puerta entre continentes</span></h1>'),
 ("<p>Where the Atlantic meets the Mediterranean — caves, capes and kasbahs at Morocco's northern door, a short sail from Spain.</p>", "<p>Donde el Atlántico se encuentra con el Mediterráneo — cuevas, cabos y kasbahs en la puerta norte de Marruecos, a un corto trayecto en barco desde España.</p>"),
 ("<span class=\"meta-item\">⛴️ Ferry port from Spain</span>", "<span class=\"meta-item\">⛴️ Puerto de ferry desde España</span>"),
 ("<span class=\"meta-item\">🕳️ Hercules Caves</span>", "<span class=\"meta-item\">🕳️ Cuevas de Hércules</span>"),
 ("<span class=\"meta-item\">🏰 Kasbah &amp; medina</span>", "<span class=\"meta-item\">🏰 Kasbah y medina</span>"),
 ("<span class=\"meta-item\">🔵 Near Chefchaouen</span>", "<span class=\"meta-item\">🔵 Cerca de Chauen</span>"),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Africa begins here</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">África empieza aquí</h2>'),
 ("Most travellers meet Tangier from the sea: ferries from Tarifa and Algeciras dock at Tanger Med and Tangier Ville, and on clear days you can see two continents at once. The city has always been a meeting point — Phoenician, Roman, Portuguese, British and international-zone pasts layered into one port town.",
  "La mayoría de los viajeros conoce Tánger desde el mar: los ferris de Tarifa y Algeciras atracan en Tánger Med y Tánger Ville, y en días despejados se ven dos continentes a la vez. La ciudad siempre ha sido un punto de encuentro — pasados fenicio, romano, portugués, británico y de zona internacional superpuestos en una sola ciudad portuaria."),
 ("The essentials fit in a day: the <strong>Caves of Hercules</strong> just west of the city, with their famous sea-shaped opening; nearby <strong>Cap Spartel</strong>, the headland where Atlantic and Mediterranean waters meet; then back into town for the <strong>kasbah</strong> — its small museum, panoramic terrace cafés — and the medina spilling down to the port.",
  "Lo esencial cabe en un día: las <strong>cuevas de Hércules</strong> al oeste de la ciudad, con su famosa abertura en forma de África; el cercano <strong>cabo Espartel</strong>, el promontorio donde se encuentran el Atlántico y el Mediterráneo; y de vuelta a la ciudad, la <strong>kasbah</strong> — su pequeño museo, sus cafés-terraza panorámicos — y la medina que desciende hasta el puerto."),
 ("Tangier pairs naturally with", "Tánger combina muy bien con"),
 ("in the Rif and the road south to", "en el Rif y la carretera hacia el sur hasta"),
 (". Starting your Morocco trip here instead of Marrakech means crowds thin out and prices drop from day one — tell us your ferry arrival and we meet you at the port.",
  ". Empezar tu viaje por Marruecos aquí en lugar de Marrakech significa menos multitudes y precios más bajos desde el primer día — dinos tu llegada en ferry y te recibiremos en el puerto."),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Highlights</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Lo más destacado</h2>'),
 ("<li><strong>Caves of Hercules</strong> — sea caves with the celebrated Africa-shaped opening.</li>", "<li><strong>Cuevas de Hércules</strong> — cuevas marinas con la célebre abertura en forma de África.</li>"),
 ("<li><strong>Cap Spartel</strong> — lighthouse headland at the meeting of two seas.</li>", "<li><strong>Cabo Espartel</strong> — promontorio del faro en el encuentro de dos mares.</li>"),
 ("<li><strong>The kasbah</strong> — museum, terrace cafés and strait views.</li>", "<li><strong>La kasbah</strong> — museo, cafés-terraza y vistas al estrecho.</li>"),
 ("<li><strong>Grand and Petit Socco</strong> — the old squares between medina and modern town.</li>", "<li><strong>Gran y Pequeño Socco</strong> — las plazas antiguas entre la medina y la ciudad moderna.</li>"),
 ("<li><strong>Onward to Chefchaouen</strong> — the Blue Pearl is a half-day south through the Rif.</li>", "<li><strong>Rumbo a Chauen</strong> — la Perla Azul está a medio día hacia el sur a través del Rif.</li>"),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:6px;">Where it is</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:6px;">Dónde está</h2>'),
 ("<p style=\"color:var(--text-muted);margin-bottom:14px;\">Morocco's northern tip, across the strait from Spain. Drag to explore.</p>", "<p style=\"color:var(--text-muted);margin-bottom:14px;\">El extremo norte de Marruecos, frente a España al otro lado del estrecho. Arrastra para explorar.</p>"),
 ('aria-label="Map of Tangier"', 'aria-label="Mapa de Tánger"'),
 ('<h2 class="day-title" style="font-size:1.8rem;margin-bottom:10px;">Arriving by ferry?</h2>', '<h2 class="day-title" style="font-size:1.8rem;margin-bottom:10px;">¿Llegas en ferry?</h2>'),
 ("<p style=\"color:var(--text-muted);max-width:640px;margin:0 auto 22px;\">Send your ferry details — we meet you at the port and your northern Morocco route starts immediately.</p>", "<p style=\"color:var(--text-muted);max-width:640px;margin:0 auto 22px;\">Envíanos los datos de tu ferry — te recibimos en el puerto y tu ruta por el norte de Marruecos empieza de inmediato.</p>"),
 ('>Plan My Trip</a>', '>Planifica mi viaje</a>'),
 ('>Chefchaouen Day Trip</a>', '>Excursión a Chauen</a>'),
 ("<h2>Tangier in photos</h2>", "<h2>Tánger en fotos</h2>"),
 ("<p>Real shots from our routes around Tangier. All photos from the Abrid Morocco local library.</p>", "<p>Fotos reales de nuestras rutas por Tánger. Todas las fotos son de la biblioteca local de Abrid Morocco.</p>"),
 ('alt="Tangier Strait of Gibraltar ferry port north Morocco"', 'alt="Puerto de ferry del estrecho de Gibraltar en Tánger, norte de Marruecos"'),
 ('alt="Cap Spartel lighthouse where Atlantic meets Mediterranean Morocco"', 'alt="Faro del cabo Espartel donde el Atlántico se une al Mediterráneo, Marruecos"'),
 ('alt="Caves of Hercules sea opening near Tangier Morocco"', 'alt="Abertura marina de las cuevas de Hércules cerca de Tánger, Marruecos"'),
 ('alt="Tangier kasbah terrace cafes overlooking the Strait Morocco"', 'alt="Cafés-terraza de la kasbah de Tánger con vistas al estrecho, Marruecos"'),
 ('alt="Grand Socco medina gateway in Tangier Morocco"', 'alt="Puerta de la medina en el Gran Socco de Tánger, Marruecos"'),
 ('alt="Tangier old port fishing boats at sunset Morocco"', 'alt="Barcos de pesca del puerto viejo de Tánger al atardecer, Marruecos"'),
 ('<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Abrid Morocco logo"', '<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Logotipo de Abrid Morocco"'),
]

TETOUAN_ES = [
 ("<title>Tetouan: The White Dove of the North | Abrid Morocco</title>", "<title>Tetuán: la Paloma blanca del norte | Abrid Morocco</title>"),
 ('content="Tetouan guide: UNESCO-listed medina, Andalusian quarter and Spanish-Moroccan history between Tangier and Chefchaouen. Visit with Abrid Morocco."', 'content="Guía de Tetuán: medina Patrimonio de la UNESCO, barrio andalusí e historia hispano-marroquí entre Tánger y Chauen. Visita con Abrid Morocco."'),
 ('content="Tetouan: The White Dove of the North | Abrid Morocco"', 'content="Tetuán: la Paloma blanca del norte | Abrid Morocco"'),
 ('content="A whitewashed UNESCO medina with Andalusian soul — between Tangier and Chefchaouen."', 'content="Una medina UNESCO encalada de blanco con alma andalusí — entre Tánger y Chauen."'),
 ('content="Tetouan: The White Dove of the North"', 'content="Tetuán: la Paloma blanca del norte"'),
 ('content="UNESCO medina, Andalusian heritage and the Rif foothills — visiting Tetouan."', 'content="Medina UNESCO, herencia andalusí y estribaciones del Rif — visitar Tetuán."'),
 ('"name":"Tetouan","description":"Northern Moroccan city with a UNESCO-listed medina and Andalusian heritage, between Tangier and Chefchaouen."', '"name":"Tetuán","description":"Ciudad del norte de Marruecos con una medina Patrimonio de la UNESCO y herencia andalusí, entre Tánger y Chauen."'),
 ('"name":"Tetouan","item":"https://www.abridmorocco.com/es/destination-tetouan.html"', '"name":"Tetuán","item":"https://www.abridmorocco.com/es/destination-tetouan.html"'),
 ('"name":"Home","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinations"', '"name":"Inicio","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinos"'),
 ('<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="https://www.abridmorocco.com/index.html">Home</a><span>/</span><a href="https://www.abridmorocco.com/destinations.html">Destinations</a><span>/</span><span>Tetouan</span></nav>',
  '<nav class="breadcrumbs" aria-label="Migas de pan"><a href="https://www.abridmorocco.com/index.html">Inicio</a><span>/</span><a href="https://www.abridmorocco.com/destinations.html">Destinos</a><span>/</span><span>Tetuán</span></nav>'),
 ('aria-label="Breadcrumb"', 'aria-label="Migas de pan"'),
 ('<span class="eyebrow">Destination · North Morocco</span>', '<span class="eyebrow">Destino · Norte de Marruecos</span>'),
 ('<h1>Tetouan: <span class="highlight">The White Dove</span></h1>', '<h1>Tetuán: <span class="highlight">la Paloma blanca</span></h1>'),
 ("<p>A whitewashed UNESCO medina with Andalusian soul — Tetouan sits between Tangier and Chefchaouen, and most travellers pass it by. Don't.</p>",
  "<p>Una medina UNESCO encalada de blanco con alma andalusí — Tetuán está entre Tánger y Chauen, y la mayoría de los viajeros pasa de largo. No lo hagas.</p>"),
 ("<span class=\"meta-item\">🏛️ UNESCO medina</span>", "<span class=\"meta-item\">🏛️ Medina UNESCO</span>"),
 ("<span class=\"meta-item\">🎭 Andalusian heritage</span>", "<span class=\"meta-item\">🎭 Herencia andalusí</span>"),
 ("<span class=\"meta-item\">⛰️ Rif foothills</span>", "<span class=\"meta-item\">⛰️ Estribaciones del Rif</span>"),
 ("<span class=\"meta-item\">🔵 Near Chefchaouen</span>", "<span class=\"meta-item\">🔵 Cerca de Chauen</span>"),
 ('alt="Painted lanes in a northern Moroccan medina"', 'alt="Callejones pintados de una medina del norte de Marruecos"'),
 ('alt="Blue doors and lanes in a northern Moroccan medina"', 'alt="Puertas azules y callejones de una medina del norte de Marruecos"'),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">The medina nobody crowds</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">La medina sin multitudes</h2>'),
 ("Rebuilt by Andalusian refugees and later capital of the Spanish protectorate, Tetouan carries a Spanish-Moroccan character found nowhere else in the country. Its medina — listed by UNESCO — is considered one of the most complete and least altered in Morocco, and you will often have its lanes almost to yourself.",
  "Reconstruida por refugiados andalusíes y más tarde capital del protectorado español, Tetuán tiene un carácter hispano-marroquí único en el país. Su medina — declarada por la UNESCO — se considera una de las más completas y menos alteradas de Marruecos, y a menudo tendrás sus callejones casi para ti."),
 ("Tetouan works best as part of a northern loop:", "Tetuán se disfruta mejor dentro de una ruta del norte:"),
 ("for arrival, Tetouan for the medina morning, then up into the Rif to", "para la llegada, Tetuán para la mañana en la medina y luego subida al Rif hasta"),
 (". Tell us your ferry or flight arrival and we sequence the north around it.", ". Dinos tu llegada en ferry o avión y organizamos el norte en consecuencia."),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Highlights</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Lo más destacado</h2>'),
 ("<li><strong>UNESCO medina</strong> — whitewashed lanes, seven gates and artisan quarters.</li>", "<li><strong>Medina UNESCO</strong> — callejones encalados, siete puertas y barrios artesanos.</li>"),
 ("<li><strong>Place Hassan II (El Feddan)</strong> — the grand square facing the Royal Palace.</li>", "<li><strong>Plaza Hasán II (El Feddan)</strong> — la gran plaza frente al Palacio Real.</li>"),
 ("<li><strong>Archaeological Museum</strong> — Roman mosaics from Lixus and Volubilis.</li>", "<li><strong>Museo arqueológico</strong> — mosaicos romanos de Lixus y Volúbilis.</li>"),
 ("<li><strong>Andalusian crafts</strong> — zellige tilework, embroidery and painted wood.</li>", "<li><strong>Artesanía andalusí</strong> — alicatado, bordado y madera pintada.</li>"),
 ("<li><strong>Martil beach</strong> — the town beach, minutes from the medina.</li>", "<li><strong>Playa de Martil</strong> — la playa de la ciudad, a minutos de la medina.</li>"),
 ("<strong>How we recommend experiencing Tetouan.</strong> Arrive mid-morning from Tangier, walk the medina with a local guide, visit the museum, lunch in the new town — then continue to Chefchaouen for sunset. Travellers often miss the museum; don't. <strong>How long:</strong> half a day is enough, a full day with the beach. <strong>How we connect it:</strong> Tangier → Tetouan → Chefchaouen →",
  "<strong>Cómo recomendamos vivir Tetuán.</strong> Llegada a media mañana desde Tánger, paseo por la medina con guía local, museo, almuerzo en la ciudad nueva y continuación a Chauen para el atardecer. Muchos viajeros se pierden el museo; no lo hagas. <strong>Duración:</strong> medio día basta, un día entero con la playa. <strong>Nuestra conexión:</strong> Tánger → Tetuán → Chauen →"),
 ("is our classic northern route.", "es nuestra clásica ruta del norte."),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Good to know</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Conviene saber</h2>'),
 ('<h3 style="font-weight:500;font-size:1.1rem;margin:0 0 6px;">How to get there</h3>', '<h3 style="font-weight:500;font-size:1.1rem;margin:0 0 6px;">Cómo llegar</h3>'),
 ("Tetouan has no train station — it is reached by road. Expect about an hour from Tangier and a similar drive from Chefchaouen by grand taxi or bus; the nearest airports are Tangier and Fes. With Abrid, your driver meets you and the route simply flows through.",
  "Tetuán no tiene estación de tren — se llega por carretera. Calcula una hora desde Tánger y un trayecto similar desde Chauen en gran taxi o autobús; los aeropuertos más cercanos son Tánger y Fez. Con Abrid, tu conductor te recibe y la ruta fluye sin más."),
 ('<h3 style="font-weight:500;font-size:1.1rem;margin:18px 0 6px;">How long to stay</h3>', '<h3 style="font-weight:500;font-size:1.1rem;margin:18px 0 6px;">Cuánto tiempo quedarse</h3>'),
 ("We recommend half a day for the medina and museum, a full day if you want the beach too. Most travellers sleep in Tangier or Chefchaouen.",
  "Recomendamos medio día para la medina y el museo, un día entero si quieres también la playa. La mayoría duerme en Tánger o Chauen."),
 ('<h3 style="font-weight:500;font-size:1.1rem;margin:18px 0 6px;">Best time to visit</h3>', '<h3 style="font-weight:500;font-size:1.1rem;margin:18px 0 6px;">Mejor época</h3>'),
 ("Spring (March–May) and autumn (September–November) are generally the most pleasant. Summer works well here thanks to the northern breeze.",
  "La primavera (marzo–mayo) y el otoño (septiembre–noviembre) suelen ser lo más agradable. El verano funciona bien aquí gracias a la brisa del norte."),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:6px;">Best areas to visit in Tetouan</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:6px;">Mejores zonas que visitar en Tetuán</h2>'),
 ("<p style=\"color:var(--text-muted);margin-bottom:14px;\">Three pockets cover the city — medina, Spanish quarter and sea.</p>", "<p style=\"color:var(--text-muted);margin-bottom:14px;\">Tres zonas cubren la ciudad: medina, barrio español y mar.</p>"),
 ("<span class=\"discover-src\">UNESCO MEDINA</span><h4>Old lanes &amp; gates</h4><p>Whitewashed alleys, seven gates and artisan quarters — the essential walk.</p>",
  "<span class=\"discover-src\">MEDINA UNESCO</span><h4>Callejones y puertas</h4><p>Callejones encalados, siete puertas y barrios artesanos: el paseo esencial.</p>"),
 ("<span class=\"discover-src\">SPANISH QUARTER</span><h4>Feddan &amp; Ensanche</h4><p>Grand square, Royal Palace exterior and café-lined avenues.</p>",
  "<span class=\"discover-src\">BARRIO ESPAÑOL</span><h4>Feddan y Ensanche</h4><p>Gran plaza, exterior del Palacio Real y avenidas con cafés.</p>"),
 ("<span class=\"discover-src\">COAST</span><h4>Martil beach</h4><p>Town beach minutes away for a sea breather after the medina.</p>",
  "<span class=\"discover-src\">COSTA</span><h4>Playa de Martil</h4><p>Playa urbana a minutos para respirar el mar tras la medina.</p>"),
 ('aria-label="Map of Tetouan areas"', 'aria-label="Mapa de las zonas de Tetuán"'),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Trips visiting Tetouan</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Viajes que pasan por Tetuán</h2>'),
 ("<div class=\"dest-tour\"><h3>Private Custom Trips</h3><p>Northern Morocco built around you — Tangier, Tetouan, Chefchaouen and beyond.</p>", "<div class=\"dest-tour\"><h3>Viajes privados a medida</h3><p>El norte de Marruecos a tu medida: Tánger, Tetuán, Chauen y más allá.</p>"),
 ('>View tour</a>', '>Ver el tour</a>'),
 ("No fixed Tetouan trip yet?", "¿Aún no hay viaje fijo a Tetuán?"),
 ("and we build it into a northern route.", "y lo integraremos en una ruta del norte."),
 ('>Tell us your dates</a>', '>Dinos tus fechas</a>'),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Morocco guides</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Guías de Marruecos</h2>'),
 ("<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-destinations.html\"><h3>Destinations Guide</h3><p>Marrakech to Chefchaouen →</p></a>", "<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-destinations.html\"><h3>Guía de destinos</h3><p>De Marrakech a Chauen →</p></a>"),
 ("<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-best-time.html\"><h3>Best Time to Visit</h3><p>Seasons by region →</p></a>", "<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-best-time.html\"><h3>Mejor época</h3><p>Estaciones por región →</p></a>"),
 ("<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-transport.html\"><h3>Transport Guide</h3><p>Trains, buses &amp; cars →</p></a>", "<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-transport.html\"><h3>Guía de transporte</h3><p>Trenes, autobuses y coches →</p></a>"),
 ("<a class=\"related-card\" href=\"https://www.abridmorocco.com/blog-chefchaouen.html\"><h3>Chefchaouen Guide</h3><p>The Blue Pearl →</p></a>", "<a class=\"related-card\" href=\"https://www.abridmorocco.com/blog-chefchaouen.html\"><h3>Guía de Chauen</h3><p>La Perla Azul →</p></a>"),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Tetouan questions</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Preguntas sobre Tetuán</h2>'),
 ("<summary>Is Tetouan worth visiting?</summary><p>Yes if you are passing through the north — its UNESCO medina is among Morocco's best preserved and far less crowded than Fes or Marrakech. As a half-day stop between Tangier and Chefchaouen it is excellent.</p>",
  "<summary>¿Merece la pena visitar Tetuán?</summary><p>Sí si pasas por el norte: su medina UNESCO está entre las mejor conservadas de Marruecos y mucho menos concurrida que Fez o Marrakech. Como parada de medio día entre Tánger y Chauen es excelente.</p>"),
 ("<summary>How do I combine Tetouan with Chefchaouen?</summary><p>Easily: the two are about an hour apart by road. Our classic northern route runs Tangier → Tetouan → Chefchaouen → Fes.",
  "<summary>¿Cómo combino Tetuán con Chauen?</summary><p>Fácil: están a una hora por carretera. Nuestra clásica ruta del norte va Tánger → Tetuán → Chauen → Fez."),
 ('>Plan it with us</a>.', '>Planifícalo con nosotros</a>.'),
 ("<summary>Can I get there by train?</summary><p>No — Tetouan has no train station. You arrive by road from Tangier, Chefchaouen or Fes. With Abrid, private transport is already part of your itinerary.</p>",
  "<summary>¿Puedo llegar en tren?</summary><p>No: Tetuán no tiene estación. Se llega por carretera desde Tánger, Chauen o Fez. Con Abrid, el transporte privado ya forma parte de tu itinerario.</p>"),
 ("<h2>Tetouan in photos</h2>", "<h2>Tetuán en fotos</h2>"),
 ("<p>Real shots from our routes around Tetouan. All photos from the Abrid Morocco local library.</p>", "<p>Fotos reales de nuestras rutas por Tetuán. Todas las fotos son de la biblioteca local de Abrid Morocco.</p>"),
 ('alt="Tetouan UNESCO whitewashed medina lanes north Morocco"', 'alt="Callejones encalados de la medina UNESCO de Tetuán, norte de Marruecos"'),
 ('alt="Place Hassan II Feddan square Royal Palace Tetouan Morocco"', 'alt="Plaza Hasán II, Feddan y Palacio Real de Tetuán, Marruecos"'),
 ('alt="Andalusian zellige tilework artisan quarter Tetouan Morocco"', 'alt="Alicatado andalusí del barrio artesano de Tetuán, Marruecos"'),
 ('alt="Tetouan medina historic seven gates old walls Morocco"', 'alt="Siete puertas históricas y murallas de la medina de Tetuán, Marruecos"'),
 ('alt="Archaeological Museum Roman mosaics Tetouan Morocco"', 'alt="Mosaicos romanos del museo arqueológico de Tetuán, Marruecos"'),
 ('alt="Spanish quarter Ensanche avenues Tetouan Morocco"', 'alt="Avenidas del barrio español del Ensanche de Tetuán, Marruecos"'),
 ('alt="Martil beach coastline near Tetouan Morocco"', 'alt="Costa de la playa de Martil cerca de Tetuán, Marruecos"'),
 ('alt="Rif foothills panorama over Tetouan Morocco"', 'alt="Panorama de las estribaciones del Rif sobre Tetuán, Marruecos"'),
 ("<h2>Want to include Tetouan in your Morocco trip?</h2>", "<h2>¿Quieres incluir Tetuán en tu viaje a Marruecos?</h2>"),
 ("<p>Tell us your dates and interests — we fit Tetouan into a northern Morocco route with transport, stays and guides handled.</p>", "<p>Dinos tus fechas e intereses: integramos Tetuán en una ruta del norte de Marruecos con transporte, alojamientos y guías incluidos.</p>"),
 ('>Plan My Morocco Trip</a>', '>Planifica mi viaje a Marruecos</a>'),
 ('>Explore Trips</a>', '>Explorar viajes</a>'),
 ('<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Abrid Morocco logo"', '<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Logotipo de Abrid Morocco"'),
]
