# -*- coding: utf-8 -*-
ASILAH_FR = [
 ("<title>Asilah: The Artists' Town on the Atlantic | Abrid Morocco</title>", "<title>Asilah : la ville des artistes sur l\u2019Atlantique | Abrid Morocco</title>"),
 ('content="Asilah guide: whitewashed medina, Portuguese ramparts, festival murals and Atlantic beaches south of Tangier. Visit with Abrid Morocco."', 'content="Guide d\u2019Asilah : m\u00e9dina blanchie \u00e0 la chaux, remparts portugais, fresques du festival et plages atlantiques au sud de Tanger. Visitez avec Abrid Morocco."'),
 ('content="Asilah: The Artists\' Town on the Atlantic | Abrid Morocco"', 'content="Asilah : la ville des artistes sur l\u2019Atlantique | Abrid Morocco"'),
 ('content="Whitewashed lanes, painted murals and ocean ramparts — a slow Atlantic stop south of Tangier."', 'content="Ruelles blanchies, fresques peintes et remparts face \u00e0 l\u2019oc\u00e9an — une douce escale atlantique au sud de Tanger."'),
 ('content="Asilah: The Artists\' Town on the Atlantic"', 'content="Asilah : la ville des artistes sur l\u2019Atlantique"'),
 ('content="Murals, medina and Atlantic beaches — visiting Asilah."', 'content="Fresques, m\u00e9dina et plages atlantiques — visiter Asilah."'),
 ('"name":"Asilah","description":"Atlantic coastal town south of Tangier with a whitewashed medina, Portuguese ramparts and an annual arts festival."', '"name":"Asilah","description":"Ville c\u00f4ti\u00e8re atlantique au sud de Tanger avec une m\u00e9dina blanchie \u00e0 la chaux, des remparts portugais et un festival d\u2019art annuel."'),
 ('"name":"Asilah","item":"https://www.abridmorocco.com/fr/destination-asilah.html"', '"name":"Asilah","item":"https://www.abridmorocco.com/fr/destination-asilah.html"'),
 ('"name":"Home","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinations"', '"name":"Accueil","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinations"'),
 ('<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="https://www.abridmorocco.com/index.html">Home</a><span>/</span><a href="https://www.abridmorocco.com/destinations.html">Destinations</a><span>/</span><span>Asilah</span></nav>',
  '<nav class="breadcrumbs" aria-label="Fil d\u2019Ariane"><a href="https://www.abridmorocco.com/index.html">Accueil</a><span>/</span><a href="https://www.abridmorocco.com/destinations.html">Destinations</a><span>/</span><span>Asilah</span></nav>'),
 ('aria-label="Breadcrumb"', 'aria-label="Fil d\u2019Ariane"'),
 ('<span class="eyebrow">Destination · North Morocco</span>', '<span class="eyebrow">Destination · Nord du Maroc</span>'),
 ('<h1>Asilah: <span class="highlight">The Artists\' Town</span></h1>', '<h1>Asilah : <span class="highlight">la ville des artistes</span></h1>'),
 ("<p>Whitewashed lanes, painted murals and Portuguese ramparts over the Atlantic — Asilah is the north's slowest, gentlest stop.</p>",
  "<p>Ruelles blanchies, fresques peintes et remparts portugais face \u00e0 l\u2019Atlantique — Asilah est l\u2019escale la plus douce et la plus paisible du nord.</p>"),
 ("<span class=\"meta-item\">🎨 Festival murals</span>", "<span class=\"meta-item\">🎨 Fresques du festival</span>"),
 ("<span class=\"meta-item\">🏰 Portuguese ramparts</span>", "<span class=\"meta-item\">🏰 Remparts portugais</span>"),
 ("<span class=\"meta-item\">🏖️ Atlantic beaches</span>", "<span class=\"meta-item\">🏖️ Plages atlantiques</span>"),
 ("<span class=\"meta-item\">🚂 Rail from Tangier</span>", "<span class=\"meta-item\">🚂 Train depuis Tanger</span>"),
 ('alt="Ramparts and boats on Morocco\'s Atlantic coast"', 'alt="Remparts et bateaux sur la c\u00f4te atlantique du Maroc"'),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Murals, medina, ocean</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Fresques, m\u00e9dina, oc\u00e9an</h2>'),
 ("Every year the town's cultural festival invites artists to repaint the medina walls, so Asilah's lanes are an open-air gallery that changes with the seasons. Behind Portuguese-era ramparts you find a compact whitewashed medina, a small fishing port and long sandy beaches — including the well-known Paradise Beach just south of town.",
  "Chaque ann\u00e9e, le festival culturel de la ville invite des artistes \u00e0 repeindre les murs de la m\u00e9dina : les ruelles d\u2019Asilah forment ainsi une galerie \u00e0 ciel ouvert qui change au fil des saisons. Derri\u00e8re les remparts de l\u2019\u00e9poque portugaise se cachent une m\u00e9dina compacte blanchie \u00e0 la chaux, un petit port de p\u00eache et de longues plages de sable — dont la c\u00e9l\u00e8bre plage Paradise juste au sud de la ville."),
 ("Asilah suits travellers moving between", "Asilah convient aux voyageurs qui se d\u00e9placent entre"),
 ("who want one slow coastal pause. Half a day covers the medina and ramparts; stay for sunset and the town earns its reputation.",
  "et qui veulent une douce pause c\u00f4ti\u00e8re. Une demi-journ\u00e9e suffit pour la m\u00e9dina et les remparts ; restez pour le coucher du soleil et la ville m\u00e9ritera sa r\u00e9putation."),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Highlights</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Points forts</h2>'),
 ("<li><strong>Medina murals</strong> — repainted festival artworks on whitewashed walls.</li>", "<li><strong>Fresques de la m\u00e9dina</strong> — \u0153uvres du festival repeintes sur des murs blanchis \u00e0 la chaux.</li>"),
 ("<li><strong>Portuguese ramparts</strong> — sea walls and the old El-Kamra tower.</li>", "<li><strong>Remparts portugais</strong> — remparts marins et vieille tour El-Kamra.</li>"),
 ("<li><strong>Fishing port</strong> — watch the afternoon boats come in.</li>", "<li><strong>Port de p\u00eache</strong> — regardez les bateaux rentrer l\u2019apr\u00e8s-midi.</li>"),
 ("<li><strong>Paradise Beach</strong> — long sand south of town.</li>", "<li><strong>Plage Paradise</strong> — longue \u00e9tendue de sable au sud de la ville.</li>"),
 ("<li><strong>Sunset on the ramparts</strong> — Asilah's essential evening hour.</li>", "<li><strong>Coucher de soleil sur les remparts</strong> — l\u2019heure du soir incontournable d\u2019Asilah.</li>"),
 ("<strong>How we recommend experiencing Asilah.</strong> Morning in the medina before the day-trippers, grilled fish lunch at the port, beach afternoon, sunset on the walls. <strong>How long:</strong> half a day to one night. <strong>What travellers miss:</strong> the murals change yearly — ask a local which walls are new. <strong>How we connect it:</strong> Tangier → Asilah → Rabat is the natural Atlantic drive south.",
  "<strong>Notre fa\u00e7on recommand\u00e9e de d\u00e9couvrir Asilah.</strong> Matin\u00e9e dans la m\u00e9dina avant les excursionnistes, d\u00e9jeuner de poisson grill\u00e9 au port, apr\u00e8s-midi \u00e0 la plage, coucher de soleil sur les remparts. <strong>Dur\u00e9e :</strong> une demi-journ\u00e9e \u00e0 une nuit. <strong>Ce que les voyageurs ratent :</strong> les fresques changent chaque ann\u00e9e — demandez \u00e0 un habitant quels murs sont nouveaux. <strong>Notre liaison :</strong> Tanger → Asilah → Rabat, c\u2019est la route atlantique naturelle vers le sud."),
 ('<h3 style="font-weight:500;font-size:1.1rem;margin:0 0 6px;">How to get there</h3>', '<h3 style="font-weight:500;font-size:1.1rem;margin:0 0 6px;">Comment y aller</h3>'),
 ("Asilah sits on the Tangier–Casablanca rail line, so trains from Tangier and Rabat stop here; by road it is roughly an hour south of Tangier. With Abrid, the stop is simply folded into your Atlantic route.",
  "Asilah se trouve sur la ligne ferroviaire Tanger–Casablanca : les trains de Tanger et de Rabat s\u2019y arr\u00eatent ; par la route, comptez environ une heure au sud de Tanger. Avec Abrid, l\u2019escale s\u2019int\u00e8gre simplement \u00e0 votre itin\u00e9raire atlantique."),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Good to know</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Bon \u00e0 savoir</h2>'),
 ('<h3 style="font-weight:500;font-size:1.1rem;margin:18px 0 6px;">How long to stay</h3>', '<h3 style="font-weight:500;font-size:1.1rem;margin:18px 0 6px;">Combien de temps rester</h3>'),
 ("We recommend half a day for the medina and ramparts, or one night to catch sunset and the beach. Few travellers need longer.",
  "Nous recommandons une demi-journ\u00e9e pour la m\u00e9dina et les remparts, ou une nuit pour profiter du coucher de soleil et de la plage. Peu de voyageurs ont besoin de plus."),
 ('<h3 style="font-weight:500;font-size:1.1rem;margin:18px 0 6px;">Best time to visit</h3>', '<h3 style="font-weight:500;font-size:1.1rem;margin:18px 0 6px;">Meilleure p\u00e9riode</h3>'),
 ("Spring (March–May) and autumn (September–November) are generally ideal; summer brings beach weather and the cultural festival season.",
  "Le printemps (mars–mai) et l\u2019automne (septembre–novembre) sont g\u00e9n\u00e9ralement id\u00e9aux ; l\u2019\u00e9t\u00e9 apporte le temps de plage et la saison du festival culturel."),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:6px;">Best areas to visit in Asilah</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:6px;">Meilleurs quartiers \u00e0 visiter \u00e0 Asilah</h2>'),
 ("<p style=\"color:var(--text-muted);margin-bottom:14px;\">Compact town, three zones — medina, walls and sand.</p>", "<p style=\"color:var(--text-muted);margin-bottom:14px;\">Ville compacte, trois zones — m\u00e9dina, remparts et sable.</p>"),
 ("<span class=\"discover-src\">MEDINA</span><h4>Murals &amp; lanes</h4><p>Repainted festival artworks on whitewashed walls around every corner.</p>",
  "<span class=\"discover-src\">M\u00c9DINA</span><h4>Fresques et ruelles</h4><p>\u0152uvres du festival repeintes sur des murs blanchis \u00e0 chaque coin de rue.</p>"),
 ("<span class=\"discover-src\">RAMPARTS</span><h4>Walls &amp; tower</h4><p>Sea walls, El-Kamra tower and the sunset walk above the ocean.</p>",
  "<span class=\"discover-src\">REMPARTS</span><h4>Murs et tour</h4><p>Remparts marins, tour El-Kamra et promenade au coucher du soleil au-dessus de l\u2019oc\u00e9an.</p>"),
 ("<span class=\"discover-src\">BEACH</span><h4>Paradise Beach</h4><p>Long sand south of town for swimming and slow afternoons.</p>",
  "<span class=\"discover-src\">PLAGE</span><h4>Plage Paradise</h4><p>Longue plage au sud de la ville pour la baignade et les apr\u00e8s-midis tranquilles.</p>"),
 ('aria-label="Map of Asilah areas"', 'aria-label="Carte des quartiers d\u2019Asilah"'),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Trips visiting Asilah</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Circuits passant par Asilah</h2>'),
 ("<div class=\"dest-tour\"><h3>Private Custom Trips</h3><p>Atlantic Morocco built around you — Asilah, Rabat, Casablanca and the coast.</p>", "<div class=\"dest-tour\"><h3>Circuits priv\u00e9s sur mesure</h3><p>Le Maroc atlantique construit autour de vous — Asilah, Rabat, Casablanca et la c\u00f4te.</p>"),
 ('>View tour</a>', '>Voir le circuit</a>'),
 ("No fixed Asilah trip yet?", "Pas encore de circuit fixe \u00e0 Asilah ?"),
 ("and we add it to a coastal route.", "et nous l\u2019ajouterons \u00e0 un itin\u00e9raire c\u00f4tier."),
 ('>Tell us your dates</a>', '>Indiquez-nous vos dates</a>'),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Morocco guides</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Guides du Maroc</h2>'),
 ("<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-destinations.html\"><h3>Destinations Guide</h3><p>Marrakech to Chefchaouen →</p></a>", "<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-destinations.html\"><h3>Guide des destinations</h3><p>De Marrakech \u00e0 Chefchaouen →</p></a>"),
 ("<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-best-time.html\"><h3>Best Time to Visit</h3><p>Seasons by region →</p></a>", "<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-best-time.html\"><h3>Meilleure p\u00e9riode</h3><p>Les saisons par r\u00e9gion →</p></a>"),
 ("<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-transport.html\"><h3>Transport Guide</h3><p>Trains, buses &amp; cars →</p></a>", "<a class=\"related-card\" href=\"https://www.abridmorocco.com/guide-transport.html\"><h3>Guide des transports</h3><p>Trains, bus et voitures →</p></a>"),
 ("<h3>Tangier Guide</h3><p>The northern door →</p>", "<h3>Guide de Tanger</h3><p>La porte du nord →</p>"),
 ('<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Asilah questions</h2>', '<h2 class="day-title" style="font-size:1.6rem;margin-bottom:14px;">Questions sur Asilah</h2>'),
 ("<summary>Is Asilah worth a stop?</summary><p>Yes as a half-day coastal pause between Tangier and Rabat — the murals, ramparts and sunset are the draw. It is a restful town rather than a full-day destination.</p>",
  "<summary>Asilah vaut-elle une escale ?</summary><p>Oui comme pause c\u00f4ti\u00e8re d\u2019une demi-journ\u00e9e entre Tanger et Rabat — les fresques, les remparts et le coucher de soleil sont l\u2019attrait. C\u2019est une ville reposante plut\u00f4t qu\u2019une destination pour la journ\u00e9e.</p>"),
 ("<summary>When is the arts festival?</summary><p>The cultural moussem usually runs in summer, when new murals are painted. Dates shift yearly — ask us when planning and we will check what is on.</p>",
  "<summary>Quand a lieu le festival d\u2019art ?</summary><p>Le moussem culturel a g\u00e9n\u00e9ralement lieu en \u00e9t\u00e9, quand les nouvelles fresques sont peintes. Les dates changent chaque ann\u00e9e — demandez-nous lors de la planification et nous v\u00e9rifierons le programme.</p>"),
 ("<summary>Can Abrid include Asilah in my trip?</summary><p>Easily — it slots into any Tangier-to-Rabat coastal drive.", "<summary>Abrid peut-il inclure Asilah dans mon voyage ?</summary><p>Facilement — elle s\u2019int\u00e8gre \u00e0 tout trajet c\u00f4tier de Tanger \u00e0 Rabat."),
 ('>Request it here</a>.', '>Demandez-la ici</a>.'),
 ("<h2>Asilah in photos</h2>", "<h2>Asilah en photos</h2>"),
 ("<p>Real shots from our routes around Asilah. All photos from the Abrid Morocco local library.</p>", "<p>Photos r\u00e9elles de nos itin\u00e9raires autour d\u2019Asilah. Toutes les photos viennent de la phototh\u00e8que locale d\u2019Abrid Morocco.</p>"),
 ('alt="Asilah festival murals whitewashed medina lanes Morocco"', 'alt="Fresques du festival et ruelles blanchies de la m\u00e9dina d\u2019Asilah, Maroc"'),
 ('alt="Portuguese ramparts El-Kamra tower Asilah Atlantic Morocco"', 'alt="Remparts portugais et tour El-Kamra \u00e0 Asilah, Atlantique, Maroc"'),
 ('alt="Asilah fishing port afternoon boats Morocco"', 'alt="Bateaux de l\u2019apr\u00e8s-midi au port de p\u00eache d\u2019Asilah, Maroc"'),
 ('alt="Paradise Beach long sand south of Asilah Morocco"', 'alt="Longue plage de sable de Paradise au sud d\u2019Asilah, Maroc"'),
 ('alt="Sunset walk on Asilah sea walls Morocco"', 'alt="Promenade au coucher du soleil sur les remparts marins d\u2019Asilah, Maroc"'),
 ("<h2>Want to include Asilah in your Morocco trip?</h2>", "<h2>Envie d\u2019inclure Asilah dans votre voyage au Maroc ?</h2>"),
 ("<p>Tell us your dates and interests — we fold Asilah into an Atlantic route with transport, stays and guides handled.</p>", "<p>Indiquez-nous vos dates et vos envies — nous int\u00e9grerons Asilah \u00e0 un itin\u00e9raire atlantique avec transport, h\u00e9bergements et guides pris en charge.</p>"),
 ('>Plan My Morocco Trip</a>', '>Planifier mon voyage au Maroc</a>'),
 ('>Explore Trips</a>', '>Explorer les circuits</a>'),
 ('<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Abrid Morocco logo"', '<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Logo Abrid Morocco"'),
]

CHEF_FR = [
 ("<title>Chefchaouen Travel Guide &amp; Tours | Abrid Morocco</title>", "<title>Guide de voyage et circuits \u00e0 Chefchaouen | Abrid Morocco</title>"),
 ('content="Chefchaouen destination guide: the blue Pearl of the Rif - the medina, the Spanish Mosque viewpoint, Akchour falls, and how to include it in a Morocco route."', 'content="Guide de Chefchaouen : la Perle bleue du Rif — la m\u00e9dina, le point de vue de la Mosqu\u00e9e espagnole, les cascades d\u2019Akchour et comment l\u2019inclure dans un itin\u00e9raire au Maroc."'),
 ('content="Chefchaouen Travel Guide &amp; Tours | Abrid Morocco"', 'content="Guide de voyage et circuits \u00e0 Chefchaouen | Abrid Morocco"'),
 ('content="Chefchaouen destination guide: the blue Pearl of the Rif &mdash; the medina, the Spanish Mosque viewpoint, Akchour falls and how to include it in a Morocco route."', 'content="Guide de Chefchaouen : la Perle bleue du Rif — la m\u00e9dina, le point de vue de la Mosqu\u00e9e espagnole, les cascades d\u2019Akchour et comment l\u2019inclure dans un itin\u00e9raire au Maroc."'),
 ('"description": "Chefchaouen destination guide: the blue Pearl of the Rif &mdash; the medina, the Spanish Mosque viewpoint, Akchour falls and how to include it in a Morocco route."', '"description": "Guide de Chefchaouen : la Perle bleue du Rif — la m\u00e9dina, le point de vue de la Mosqu\u00e9e espagnole, les cascades d\u2019Akchour et comment l\u2019inclure dans un itin\u00e9raire au Maroc."'),
 ('"name": "How long should I stay?"', '"name": "Combien de temps rester ?"'),
 ('"text": "One full day for the medina and viewpoint, plus a half-day for Akchour if you enjoy walking. Many travellers stay two nights."', '"text": "Une journ\u00e9e compl\u00e8te pour la m\u00e9dina et le point de vue, plus une demi-journ\u00e9e pour Akchour si vous aimez marcher. Beaucoup de voyageurs restent deux nuits."'),
 ('"name": "Is Chefchaouen on the way anywhere?"', '"name": "Chefchaouen est-elle sur la route ?"'),
 ('"text": "It works best on a northern route linking Tangier, Fes and the Imperial Cities — which is how our classic circuits include it."', '"text": "Elle s\u2019appr\u00e9cie id\u00e9alement sur un itin\u00e9raire du nord reliant Tanger, F\u00e8s et les Cit\u00e9s imp\u00e9riales — c\u2019est ainsi que nos circuits classiques l\u2019incluent."'),
 ('"name": "Why is the town painted blue?"', '"name": "Pourquoi la ville est-elle peinte en bleu ?"'),
 ('"text": "Tradition links it to a Jewish community that settled here, and the blue is said to repel mosquitoes and keep homes cool — whatever the reason, the effect is magical."', '"text": "La tradition l\u2019attribue \u00e0 une communaut\u00e9 juive install\u00e9e ici, et le bleu repousserait les moustiques et garderait les maisons fra\u00eeches — quelle qu\u2019en soit la raison, l\u2019effet est magique."'),
 ('"name":"Chefchaouen","item":"https://www.abridmorocco.com/fr/destination-chefchaouen.html"', '"name":"Chefchaouen","item":"https://www.abridmorocco.com/fr/destination-chefchaouen.html"'),
 ('"name":"Home","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinations"', '"name":"Accueil","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinations"'),
 ('<span class="eyebrow">Abrid Morocco Destination</span>', '<span class="eyebrow">Destination Abrid Morocco</span>'),
 ('<h1>Chefchaouen</h1>', '<h1>Chefchaouen</h1>'),
 ('<p class="lead">Every shade of blue on a mountainside &mdash; Morocco&rsquo;s prettiest medina in the Rif, best seen at sunset from the Spanish Mosque.</p>',
  '<p class="lead">Toutes les nuances de bleu \u00e0 flanc de montagne — la plus jolie m\u00e9dina du Maroc dans le Rif, id\u00e9ale au coucher du soleil depuis la Mosqu\u00e9e espagnole.</p>'),
 ('>Marrakech <span class="arrow">', '>Marrakech <span class="arrow">'),
 ('>Sahara Desert <span class="arrow">', '>D\u00e9sert du Sahara <span class="arrow">'),
 ('>Fes <span class="arrow">', '>F\u00e8s <span class="arrow">'),
 ('>Essaouira <span class="arrow">', '>Essaouira <span class="arrow">'),
 ('>Atlas Mountains <span class="arrow">', '>Montagnes de l\u2019Atlas <span class="arrow">'),
 ('>Ait Benhaddou <span class="arrow">', '>A\u00eft Benhaddou <span class="arrow">'),
 ('>Agadir <span class="arrow">', '>Agadir <span class="arrow">'),
 ('<h2 style="font-weight:400;font-size:clamp(1.6rem,3vw,2.2rem);margin:0 0 8px">Chefchaouen &ndash; The Blue Pearl of the Rif</h2>', '<h2 style="font-weight:400;font-size:clamp(1.6rem,3vw,2.2rem);margin:0 0 8px">Chefchaouen – la Perle Bleue du Rif</h2>'),
 ("<p style=\"font-family:var(--font-body);color:var(--text-muted);max-width:720px;margin:0 0 28px\">A mountain town painted in every shade of blue, tucked into the Rif Mountains behind the cedar forests of the north.</p>",
  "<p style=\"font-family:var(--font-body);color:var(--text-muted);max-width:720px;margin:0 0 28px\">Une ville de montagne peinte dans toutes les nuances de bleu, nich\u00e9e dans les montagnes du Rif derri\u00e8re les for\u00eats de c\u00e8dres du nord.</p>"),
 ('<span class="fact-label">Region</span><span class="fact-value">Rif Mountains, north-west Morocco</span>', '<span class="fact-label">R\u00e9gion</span><span class="fact-value">Montagnes du Rif, nord-ouest du Maroc</span>'),
 ('<span class="fact-label">Best time</span><span class="fact-value">Apr&ndash;Oct; Akshar in early summer</span>', '<span class="fact-label">Meilleure p\u00e9riode</span><span class="fact-value">Avr–oct ; Akchour au d\u00e9but de l\u2019\u00e9t\u00e9</span>'),
 ('<span class="fact-label">Icon</span><span class="fact-value">The blue-washed medina</span>', '<span class="fact-label">Embl\u00e8me</span><span class="fact-value">La m\u00e9dina lav\u00e9e de bleu</span>'),
 ('<span class="fact-label">Star view</span><span class="fact-value">Spanish Mosque viewpoint at sunset</span>', '<span class="fact-label">Point de vue</span><span class="fact-value">Mosqu\u00e9e espagnole au coucher du soleil</span>'),
 ("<p><strong>Chefchaouen</strong> climbs a mountainside beneath the peaks of Jebel el-Kala&rsquo;a. Its medina is famous the world over for walls and stairways washed in blues &mdash; calm, photogenic and perfectly walkable in a relaxed day or two.</p>",
  "<p><strong>Chefchaouen</strong> grimpe \u00e0 flanc de montagne sous les sommets du Jebel el-Kala\u00e2. Sa m\u00e9dina est c\u00e9l\u00e8bre dans le monde entier pour ses murs et escaliers lav\u00e9s de bleu — calme, photog\u00e9nique et parfaite \u00e0 pied en un ou deux jours tranquilles.</p>"),
 ("Start in the main square <strong>Plaza Uta el-Hammam</strong> with a mint tea and a view of the <strong>Grand Mosque</strong>, wander the artisan lanes of the <strong>kasbah</strong>, then hike a short way to the <strong>Spanish Mosque</strong> for the famous panorama as the town glows blue at sunset. The <strong>Akchour waterfalls</strong> and cedar forests of the Talassemtane National Park sit a short drive away.",
  "Commencez sur la place principale <strong>Plaza Uta el-Hammam</strong> avec un th\u00e9 \u00e0 la menthe et la vue sur la <strong>Grande Mosqu\u00e9e</strong>, fl\u00e2nez dans les ruelles artisanales de la <strong>kasbah</strong>, puis marchez un peu jusqu\u2019\u00e0 la <strong>Mosqu\u00e9e espagnole</strong> pour le c\u00e9l\u00e8bre panorama quand la ville s\u2019embrase de bleu au coucher du soleil. Les <strong>cascades d\u2019Akchour</strong> et les for\u00eats de c\u00e8dres du parc national de Talassemtane sont \u00e0 courte distance en voiture."),
 ("&ldquo;Chefchaouen is the place where travellers arrive for one night and quietly extend their stay for three.&rdquo; &mdash; Karim, guide",
  "« Chefchaouen est l\u2019endroit o\u00f9 les voyageurs arrivent pour une nuit et prolongent discr\u00e8tement leur s\u00e9jour \u00e0 trois. » — Karim, guide"),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Highlights</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Points forts</h3>'),
 ("<div class=\"dest-highlight\"><h3>The Blue Medina</h3><p>Winding alleys, painted doors and stairways &mdash; plan extra battery for photos.</p></div>",
  "<div class=\"dest-highlight\"><h3>La M\u00e9dina bleue</h3><p>Ruelles sinueuses, portes peintes et escaliers — pr\u00e9voyez une batterie suppl\u00e9mentaire pour les photos.</p></div>"),
 ("<div class=\"dest-highlight\"><h3>Spanish Mosque Viewpoint</h3><p>A short uphill walk to the classic sunset panorama over the whole town.</p></div>",
  "<div class=\"dest-highlight\"><h3>Point de vue de la Mosqu\u00e9e espagnole</h3><p>Courte mont\u00e9e vers le panorama classique au coucher du soleil sur toute la ville.</p></div>"),
 ("<div class=\"dest-highlight\"><h3>Kasbah & Souk</h3><p>A 15th-century fortress, artisan crafts and a relaxed, unhurried market.</p></div>",
  "<div class=\"dest-highlight\"><h3>Kasbah et souk</h3><p>Forteresse du XVe si\u00e8cle, artisanat et march\u00e9 d\u00e9tendu sans pr\u00e9cipitation.</p></div>"),
 ("<div class=\"dest-highlight\"><h3>Akchour Waterfalls</h3><p>Gorges, natural bridges and pine-shaded river trails an hour from the town.</p></div>",
  "<div class=\"dest-highlight\"><h3>Cascades d\u2019Akchour</h3><p>Gorges, ponts naturels et sentiers ombrag\u00e9s de pins \u00e0 une heure de la ville.</p></div>"),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 8px">Best areas to visit in Chefchaouen</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 8px">Meilleurs quartiers \u00e0 visiter \u00e0 Chefchaouen</h3>'),
 ("<p style=\"color:var(--text-muted);margin-bottom:14px;\">Medina blue, hilltop views and waterfall valleys beyond.</p>", "<p style=\"color:var(--text-muted);margin-bottom:14px;\">Bleu de la m\u00e9dina, vues des collines et vall\u00e9es des cascades au-del\u00e0.</p>"),
 ("<span class=\"discover-src\">MEDINA</span><h4>Blue lanes</h4><p>Painted doors, stairways and the Uta el-Hammam square.</p>",
  "<span class=\"discover-src\">M\u00c9DINA</span><h4>Ruelles bleues</h4><p>Portes peintes, escaliers et place Uta el-Hammam.</p>"),
 ("<span class=\"discover-src\">VIEWPOINT</span><h4>Spanish Mosque hill</h4><p>Sunset panorama over the whole blue town.</p>",
  "<span class=\"discover-src\">POINT DE VUE</span><h4>Colline de la Mosqu\u00e9e espagnole</h4><p>Panorama au coucher du soleil sur toute la ville bleue.</p>"),
 ("<span class=\"discover-src\">VALLEY</span><h4>Ras El-Maa &amp; Akchour</h4><p>River springs at the medina edge, waterfalls further out.</p>",
  "<span class=\"discover-src\">VALL\u00c9E</span><h4>Ras El-Maa et Akchour</h4><p>Sources de la rivi\u00e8re au bord de la m\u00e9dina, cascades plus loin.</p>"),
 ('aria-label="Map of Chefchaouen areas"', 'aria-label="Carte des quartiers de Chefchaouen"'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Chefchaouen in Pictures</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Chefchaouen en images</h3>'),
 ('alt="Blue Medina alley in Chefchaouen Morocco"', 'alt="Ruelle de la M\u00e9dina bleue \u00e0 Chefchaouen, Maroc"'),
 ('>The Blue Medina from Above</figcaption>', '>La M\u00e9dina bleue vue d\u2019en haut</figcaption>'),
 ('alt="Blue Callejón El Asri alley in Chefchaouen"', 'alt="Ruelle bleue Callej\u00f3n El Asri \u00e0 Chefchaouen, Maroc"'),
 ('>Callejón El Asri Blue Alley</figcaption>', '>Ruelle bleue Callej\u00f3n El Asri</figcaption>'),
 ('alt="Spanish Mosque overlooking Chefchaouen"', 'alt="Mosqu\u00e9e espagnole surplombant Chefchaouen, Maroc"'),
 ('>Spanish Mosque Sunset View</figcaption>', '>Mosqu\u00e9e espagnole au coucher du soleil</figcaption>'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Taste of Chefchaouen</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Saveurs de Chefchaouen</h3>'),
 ('alt="Rif goat cheese and olives from northern Morocco"', 'alt="Fromage de ch\u00e8vre du Rif et olives du nord du Maroc"'),
 ('>Rif Goat Cheese & Olives</figcaption>', '>Fromage de ch\u00e8vre du Rif et olives</figcaption>'),
 ('alt="Moroccan mountain mint tea"', 'alt="Th\u00e9 \u00e0 la menthe des montagnes marocaines"'),
 ('>Mountain Mint Tea</figcaption>', '>Th\u00e9 \u00e0 la menthe des montagnes</figcaption>'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Trips that include Chefchaouen</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Circuits incluant Chefchaouen</h3>'),
 ("<div class=\"dest-tour\"><h3>Classic 13-Day Morocco</h3><p>The full circuit lands in the blue town after Fes, before heading south.</p>", "<div class=\"dest-tour\"><h3>Maroc classique en 13 jours</h3><p>Le circuit complet passe par la ville bleue apr\u00e8s F\u00e8s, avant de partir vers le sud.</p>"),
 ("<div class=\"dest-tour\"><h3>6-Day Christmas Journey</h3><p>Begins in Tangier via Chefchaouen and the cedar forests on the way to the desert.</p>", "<div class=\"dest-tour\"><h3>Voyage de No\u00ebl en 6 jours</h3><p>Commence \u00e0 Tanger via Chefchaouen et les for\u00eats de c\u00e8dres en route vers le d\u00e9sert.</p>"),
 ("<div class=\"dest-tour\"><h3>Private Custom Trips</h3><p>Add Chefchaouen and the Rif to your own northern route.</p>", "<div class=\"dest-tour\"><h3>Circuits priv\u00e9s sur mesure</h3><p>Ajoutez Chefchaouen et le Rif \u00e0 votre propre itin\u00e9raire du nord.</p>"),
 ('>View tour</a>', '>Voir le circuit</a>'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Good to know</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Bon \u00e0 savoir</h3>'),
 ("<h2>Chefchaouen in photos</h2>", "<h2>Chefchaouen en photos</h2>"),
 ("<p>Real shots from our routes around Chefchaouen. All photos from the Abrid Morocco local library.</p>", "<p>Photos r\u00e9elles de nos itin\u00e9raires autour de Chefchaouen. Toutes les photos viennent de la phototh\u00e8que locale d\u2019Abrid Morocco.</p>"),
 ('alt="Chefchaouen blue medina alley stairs Rif Morocco"', 'alt="Escaliers d\u2019une ruelle de la m\u00e9dina bleue de Chefchaouen, Rif, Maroc"'),
 ('alt="Plaza Uta el-Hammam Grand Mosque Chefchaouen Morocco"', 'alt="Place Uta el-Hammam et Grande Mosqu\u00e9e \u00e0 Chefchaouen, Maroc"'),
 ('alt="Spanish Mosque sunset panorama over Chefchaouen Morocco"', 'alt="Panorama au coucher du soleil depuis la Mosqu\u00e9e espagnole sur Chefchaouen, Maroc"'),
 ('alt="Akchour waterfalls trails near Chefchaouen Morocco"', 'alt="Sentiers des cascades d\u2019Akchour pr\u00e8s de Chefchaouen, Maroc"'),
 ('<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Abrid Morocco logo"', '<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Logo Abrid Morocco"'),
]

MARRA_FR = [
 ("<title>Marrakech Travel Guide &amp; Tours | Abrid Morocco</title>", "<title>Guide de voyage et circuits \u00e0 Marrakech | Abrid Morocco</title>"),
 ('content="Marrakech destination guide: the Red City, its souks, palaces and gardens - plus the best day trips into the High Atlas and Sahara."', 'content="Guide de Marrakech : la Ville Rouge, ses souks, palais et jardins — plus les meilleures excursions dans le Haut Atlas et le Sahara."'),
 ('content="Marrakech Travel Guide &amp; Tours | Abrid Morocco"', 'content="Guide de voyage et circuits \u00e0 Marrakech | Abrid Morocco"'),
 ('content="Marrakech destination guide: the Red City, its souks, palaces, gardens and the best day trips into the High Atlas and Sahara &mdash; with local Abrid Morocco guides."', 'content="Guide de Marrakech : la Ville Rouge, ses souks, palais, jardins et les meilleures excursions dans le Haut Atlas et le Sahara — avec les guides locaux d\u2019Abrid Morocco."'),
 ('"description": "Marrakech destination guide: the Red City, its souks, palaces, gardens and the best day trips into the High Atlas and Sahara &mdash; with local Abrid Morocco guides."', '"description": "Guide de Marrakech : la Ville Rouge, ses souks, palais, jardins et les meilleures excursions dans le Haut Atlas et le Sahara — avec les guides locaux d\u2019Abrid Morocco."'),
 ('"name": "How many days should I spend in Marrakech?"', '"name": "Combien de jours passer \u00e0 Marrakech ?"'),
 ('"text": "Two full days lets you cover the medina at a relaxed pace and still keep time for a rooftop meal or a day trip into the Atlas."', '"text": "Deux jours complets permettent de couvrir la m\u00e9dina \u00e0 un rythme d\u00e9tendu tout en gardant du temps pour un repas sur un toit-terrasse ou une excursion dans l\u2019Atlas."'),
 ('"name": "Is Marrakech safe for visitors?"', '"name": "Marrakech est-elle s\u00fbre pour les visiteurs ?"'),
 ('"text": "Yes. Usual city awareness applies — agree taxi fares before setting off and ignore persistent street touts. Your guide handles all the logistics for you."', '"text": "Oui. La vigilance habituelle en ville s\u2019applique — convenez du tarif du taxi avant de partir et ignorez les rabatteurs insistants. Votre guide s\u2019occupe de toute la logistique."'),
 ('"name": "Which trips start from Marrakech?"', '"name": "Quels circuits partent de Marrakech ?"'),
 ('"text": "Most of our routes do: Sahara desert tours, Atlas day trips, Essaouira, Ouzoud waterfalls and all multi-day circuits."', '"text": "La plupart de nos itin\u00e9raires : circuits dans le d\u00e9sert du Sahara, excursions dans l\u2019Atlas, Essaouira, cascades d\u2019Ouzoud et tous les circuits de plusieurs jours."'),
 ('"name":"Marrakech","item":"https://www.abridmorocco.com/fr/destination-marrakech.html"', '"name":"Marrakech","item":"https://www.abridmorocco.com/fr/destination-marrakech.html"'),
 ('"name":"Home","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinations"', '"name":"Accueil","item":"https://www.abridmorocco.com/"},{"@type":"ListItem","position":2,"name":"Destinations"'),
 ('<span class="eyebrow">Abrid Morocco Destination</span>', '<span class="eyebrow">Destination Abrid Morocco</span>'),
 ('<p class="lead">The Red City &mdash; gateway to the Sahara, the Atlas and the coast. Where Morocco begins for most travellers, guided by people who call it home.</p>',
  '<p class="lead">La Ville Rouge — porte d\u2019entr\u00e9e vers le Sahara, l\u2019Atlas et la c\u00f4te. L\u00e0 o\u00f9 le Maroc commence pour la plupart des voyageurs, guid\u00e9s par des gens qui y vivent.</p>'),
 ('>Marrakech <span class="arrow">', '>Marrakech <span class="arrow">'),
 ('>Sahara Desert <span class="arrow">', '>D\u00e9sert du Sahara <span class="arrow">'),
 ('>Fes <span class="arrow">', '>F\u00e8s <span class="arrow">'),
 ('>Essaouira <span class="arrow">', '>Essaouira <span class="arrow">'),
 ('>Atlas Mountains <span class="arrow">', '>Montagnes de l\u2019Atlas <span class="arrow">'),
 ('>Ait Benhaddou <span class="arrow">', '>A\u00eft Benhaddou <span class="arrow">'),
 ('>Agadir <span class="arrow">', '>Agadir <span class="arrow">'),
 ('<h2 style="font-weight:400;font-size:clamp(1.6rem,3vw,2.2rem);margin:0 0 8px">The Red City &ndash; Marrakech</h2>', '<h2 style="font-weight:400;font-size:clamp(1.6rem,3vw,2.2rem);margin:0 0 8px">La Ville Rouge – Marrakech</h2>'),
 ("<p style=\"font-family:var(--font-body);color:var(--text-muted);max-width:720px;margin:0 0 28px\">Palace courtyards, maze-like souks, rooftop views over Jemaa el-Fnaa and easy access to the High Atlas. Marrakech is where most Morocco journeys begin.</p>",
  "<p style=\"font-family:var(--font-body);color:var(--text-muted);max-width:720px;margin:0 0 28px\">Cours de palais, souks labyrinthiques, vues des toits sur Jemaa el-Fna et acc\u00e8s facile au Haut Atlas. Marrakech est l\u00e0 o\u00f9 commencent la plupart des voyages au Maroc.</p>"),
 ('<span class="fact-label">Region</span><span class="fact-value">South-west, near the High Atlas</span>', '<span class="fact-label">R\u00e9gion</span><span class="fact-value">Sud-ouest, pr\u00e8s du Haut Atlas</span>'),
 ('<span class="fact-label">Best time</span><span class="fact-value">Mar&ndash;May &amp; Sep&ndash;Nov</span>', '<span class="fact-label">Meilleure p\u00e9riode</span><span class="fact-value">Mars–mai et sept–nov</span>'),
 ('<span class="fact-label">Vibe</span><span class="fact-value">Historic city, markets, day-trip hub</span>', '<span class="fact-label">Ambiance</span><span class="fact-value">Ville historique, march\u00e9s, carrefour d\u2019excursions</span>'),
 ('<span class="fact-label">Base for</span><span class="fact-value">Sahara, Atlas &amp; coast trips</span>', '<span class="fact-label">Base pour</span><span class="fact-value">Sahara, Atlas et c\u00f4te</span>'),
 ("Marrakech is the gateway to southern Morocco. Around the UNESCO-listed medina you will find the 12th-century <strong>Koutoubia Mosque</strong>, the ornate <strong>Bahia Palace</strong>, the serene <strong>Majorelle Garden</strong> and the ever-moving theatre of <strong>Jemaa el-Fnaa</strong> &mdash; storytellers, musicians, food stalls and snake charmers at dusk.",
  "Marrakech est la porte d\u2019entr\u00e9e du sud du Maroc. Autour de la m\u00e9dina class\u00e9e UNESCO, vous trouverez la <strong>mosqu\u00e9e Koutoubia</strong> du XIIe si\u00e8cle, le <strong>palais Bahia</strong> orn\u00e9, le serein <strong>jardin Majorelle</strong> et le th\u00e9\u00e2tre toujours anim\u00e9 de <strong>Jemaa el-Fna</strong> — conteurs, musiciens, stands de nourriture et charmeurs de serpents au cr\u00e9puscule."),
 ("Beyond the walls, the same city is the launch point for the classic routes we run: desert experiences towards Merzouga, mountain days in the Ourika Valley, hot air balloon flights at sunrise, and a day at the Atlantic in Essaouira.",
  "Au-del\u00e0 des remparts, la m\u00eame ville est le point de d\u00e9part de nos itin\u00e9raires classiques : exp\u00e9riences dans le d\u00e9sert vers Merzouga, journ\u00e9es en montagne dans la vall\u00e9e de l\u2019Ourika, vols en montgolfi\u00e8re au lever du soleil et journ\u00e9e atlantique \u00e0 Essaouira."),
 ("&ldquo;Marrakech rewards slow mornings: mint tea on a rooftop, the call to prayer drifting over the medina, then a long lunch with a view.&rdquo; &mdash; Abdellah, founder &amp; Berber guide",
  "« Marrakech r\u00e9compense les matin\u00e9es lentes : th\u00e9 \u00e0 la menthe sur un toit-terrasse, l\u2019appel \u00e0 la pri\u00e8re flottant sur la m\u00e9dina, puis un long d\u00e9jeuner avec vue. » — Abdellah, fondateur et guide berb\u00e8re"),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Highlights</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Points forts</h3>'),
 ("<div class=\"dest-highlight\"><h3>Jemaa el-Fnaa</h3><p>The famous square &mdash; try it at sunset for food stalls, storytellers and music.</p></div>",
  "<div class=\"dest-highlight\"><h3>Jemaa el-Fna</h3><p>La c\u00e9l\u00e8bre place — essayez-la au coucher du soleil pour les stands de nourriture, les conteurs et la musique.</p></div>"),
 ("<div class=\"dest-highlight\"><h3>The Souks</h3><p>Endless lanes of leather, spices, carpets and lamps &mdash; go early and bargain kindly.</p></div>",
  "<div class=\"dest-highlight\"><h3>Les souks</h3><p>Ruelles infinies de cuir, d\u2019\u00e9pices, de tapis et de lampes — allez-y t\u00f4t et marchandez avec le sourire.</p></div>"),
 ("<div class=\"dest-highlight\"><h3>Palaces & Gardens</h3><p>Bahia Palace, El Badi and the Majorelle Garden for calm and colour.</p></div>",
  "<div class=\"dest-highlight\"><h3>Palais et jardins</h3><p>Palais Bahia, El Badi et jardin Majorelle pour le calme et les couleurs.</p></div>"),
 ("<div class=\"dest-highlight\"><h3>Rooftop Culture</h3><p>Atlas views, mint tea and slow afternoons above the medina rooftops.</p></div>",
  "<div class=\"dest-highlight\"><h3>Culture des toits-terrasses</h3><p>Vues sur l\u2019Atlas, th\u00e9 \u00e0 la menthe et apr\u00e8s-midis tranquilles au-dessus des toits de la m\u00e9dina.</p></div>"),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 8px">Best areas to visit in Marrakech</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 8px">Meilleurs quartiers \u00e0 visiter \u00e0 Marrakech</h3>'),
 ("<p style=\"color:var(--text-muted);margin-bottom:14px;\">Three worlds in one city — old medina, new town and palm belt.</p>", "<p style=\"color:var(--text-muted);margin-bottom:14px;\">Trois mondes en une ville — vieille m\u00e9dina, ville nouvelle et palmeraie.</p>"),
 ("<span class=\"discover-src\">MEDINA</span><h4>Jemaa el-Fna &amp; souks</h4><p>Square, palaces and craft lanes of the old city.</p>",
  "<span class=\"discover-src\">M\u00c9DINA</span><h4>Jemaa el-Fna et souks</h4><p>Place, palais et ruelles artisanales de la vieille ville.</p>"),
 ("<span class=\"discover-src\">NEW TOWN</span><h4>Guéliz</h4><p>Galleries, cafés and Majorelle Garden streets.</p>",
  "<span class=\"discover-src\">VILLE NOUVELLE</span><h4>Gu\u00e9liz</h4><p>Galeries, caf\u00e9s et rues du jardin Majorelle.</p>"),
 ("<span class=\"discover-src\">PALMS</span><h4>Palmeraie</h4><p>Palm estates, pools and sunset camel rides.</p>",
  "<span class=\"discover-src\">PALMIERS</span><h4>Palmeraie</h4><p>Domaines de palmiers, piscines et balades \u00e0 dos de chameau au coucher du soleil.</p>"),
 ('aria-label="Map of Marrakech areas"', 'aria-label="Carte des quartiers de Marrakech"'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Marrakech in Pictures</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Marrakech en images</h3>'),
 ('alt="Koutoubia Mosque in Marrakech at sunset"', 'alt="Mosqu\u00e9e Koutoubia \u00e0 Marrakech au coucher du soleil, Maroc"'),
 ('>Koutoubia Mosque at Sunset</figcaption>', '>Mosqu\u00e9e Koutoubia au coucher du soleil</figcaption>'),
 ('alt="Bahia Palace courtyard in Marrakech"', 'alt="Cour du palais Bahia \u00e0 Marrakech, Maroc"'),
 ('>Bahia Palace Courtyard</figcaption>', '>Cour du palais Bahia</figcaption>'),
 ('alt="Jemaa el-Fnaa square in Marrakech"', 'alt="Place Jemaa el-Fna \u00e0 Marrakech, Maroc"'),
 ('>Jemaa el-Fnaa at Dusk</figcaption>', '>Jemaa el-Fna au cr\u00e9puscule</figcaption>'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Taste of Marrakech</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Saveurs de Marrakech</h3>'),
 ('alt="Moroccan lamb tagine with prunes and almonds"', 'alt="Tajine marocain d\u2019agneau aux pruneaux et aux amandes, Maroc"'),
 ('>Lamb Tagine with Prunes & Almonds</figcaption>', '>Tajine d\u2019agneau aux pruneaux et aux amandes</figcaption>'),
 ('alt="Traditional Tanjia Marrakchia from Marrakech"', 'alt="Tanjia Marrakchia traditionnelle de Marrakech, Maroc"'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Trips from Marrakech</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Circuits au d\u00e9part de Marrakech</h3>'),
 ("<div class=\"dest-tour\"><h3>Marrakech Discovery Tour</h3><p>Palaces, souks and medina highlights in a private guided day.</p>", "<div class=\"dest-tour\"><h3>Visite d\u00e9couverte de Marrakech</h3><p>Palais, souks et points forts de la m\u00e9dina en journ\u00e9e priv\u00e9e guid\u00e9e.</p>"),
 ("<div class=\"dest-tour\"><h3>Hot Air Balloon Sunrise</h3><p>Float over the Haouz plains at dawn, then a Berber breakfast.</p>", "<div class=\"dest-tour\"><h3>Lever de soleil en montgolfi\u00e8re</h3><p>Survolez les plaines du Haouz \u00e0 l\u2019aube, puis petit-d\u00e9jeuner berb\u00e8re.</p>"),
 ("<div class=\"dest-tour\"><h3>Atlas &amp; Ourika Day Trip</h3><p>Berber villages, waterfall hikes and mountain views an hour away.</p>", "<div class=\"dest-tour\"><h3>Excursion Atlas et Ourika</h3><p>Villages berb\u00e8res, randonn\u00e9es aux cascades et vues montagneuses \u00e0 une heure.</p>"),
 ("<div class=\"dest-tour\"><h3>Essaouira Day Trip</h3><p>A breezy Atlantic medina, seafood and ramparts &mdash; a relaxed escape.</p>", "<div class=\"dest-tour\"><h3>Excursion \u00e0 Essaouira</h3><p>M\u00e9dina atlantique venteuse, fruits de mer et remparts — une escapade d\u00e9tendue.</p>"),
 ("<div class=\"dest-tour\"><h3>3-Day Sahara Desert</h3><p>The classic Merzouga route: Ait Benhaddou, Dades, Todra &amp; Erg Chebbi.</p>", "<div class=\"dest-tour\"><h3>D\u00e9sert du Sahara en 3 jours</h3><p>La route classique de Merzouga : A\u00eft Benhaddou, Dad\u00e8s, Todra et Erg Chebbi.</p>"),
 ("<div class=\"dest-tour\"><h3>Private Custom Trips</h3><p>Build your own multi-day journey across Morocco.</p>", "<div class=\"dest-tour\"><h3>Circuits priv\u00e9s sur mesure</h3><p>Construisez votre propre voyage de plusieurs jours \u00e0 travers le Maroc.</p>"),
 ('>View tour</a>', '>Voir le circuit</a>'),
 ('<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Good to know</h3>', '<h3 style="font-weight:400;font-size:1.3rem;margin:36px 0 18px">Bon \u00e0 savoir</h3>'),
 ("<h2>Marrakech in photos</h2>", "<h2>Marrakech en photos</h2>"),
 ("<p>Real shots from our routes around Marrakech. All photos from the Abrid Morocco local library.</p>", "<p>Photos r\u00e9elles de nos itin\u00e9raires autour de Marrakech. Toutes les photos viennent de la phototh\u00e8que locale d\u2019Abrid Morocco.</p>"),
 ('alt="Jemaa el-Fnaa square at dusk Marrakech Morocco"', 'alt="Place Jemaa el-Fna au cr\u00e9puscule \u00e0 Marrakech, Maroc"'),
 ('alt="Bahia Palace courtyard zellige Marrakech Morocco"', 'alt="Cour en zellige du palais Bahia \u00e0 Marrakech, Maroc"'),
 ('<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Abrid Morocco logo"', '<img src="https://i.postimg.cc/C5cbTcxk/abrid-logo-transparent.png" alt="Logo Abrid Morocco"'),
]
