# -*- coding: utf-8 -*-
import re, os
BASE = r"C:\Users\abrid\OneDrive\Documents\Default Project\abridmoroccotrip-main"
SITE = "https://www.abridmorocco.com"

COMMON_FR = [
 ("Abrid Morocco home", "Accueil Abrid Morocco"),
 ("Search Abrid Morocco", "Rechercher sur Abrid Morocco"),
 ("Chat with Abrid Morocco on WhatsApp", "Discuter avec Abrid Morocco sur WhatsApp"),
 ("Chat with Abrid on WhatsApp", "Discuter avec Abrid sur WhatsApp"),
 ('aria-label="Reserve a tour"', 'aria-label="Réserver un circuit"'),
 ('aria-label="Open menu"', 'aria-label="Ouvrir le menu"'),
 ("PREMIUM TOURS", "CIRCUITS PREMIUM"),
 ("Morocco travel platform", "Plateforme de voyage au Maroc"),
 ("Imperial Cities - private guides", "Cités impériales — guides privés"),
 ("Imperial Cities — private guides", "Cités impériales — guides privés"),
 ("characterful stays since 2022.", "hébergements de caractère depuis 2022."),
 ("Skip to main content", "Aller au contenu principal"),
 ('>Search</a>', '>Rechercher</a>'),
 ('>Reserve</button>', '>Réserver</button>'),
 ('placeholder="Search trips, destinations, guides..."', 'placeholder="Rechercher circuits, destinations, guides..."'),
 ('placeholder="Search trips, destinations, guides…"', 'placeholder="Rechercher circuits, destinations, guides…"'),
 ('aria-label="Search">', 'aria-label="Recherche">'),
 ('>Close</button>', '>Fermer</button>'),
 ('aria-label="Cookie consent"', 'aria-label="Consentement aux cookies"'),
 ('cookie policy</a>', 'politique des cookies</a>'),
 ('We use cookies to improve your experience and analyse site traffic. Read our', 'Nous utilisons des cookies pour améliorer votre expérience et analyser le trafic du site. Lisez notre'),
 ('>Accept</button>', '>Accepter</button>'),
 ('>Decline</button>', '>Refuser</button>'),
 ('<h4>Booking</h4>', '<h4>Réservation</h4>'),
 ('>How Booking Works</a>', '>Comment fonctionne la réservation</a>'),
 ('>Cancellation Policy</a>', '>Politique d\u2019annulation</a>'),
 ('>Terms of Service</a>', '>Conditions d\u2019utilisation</a>'),
 ('>Airport Transfer</a>', '>Transfert aéroport</a>'),
 ('<h4>Company</h4>', '<h4>Société</h4>'),
 ('>About Us</a>', '>À propos de nous</a>'),
 ('>Gallery</a>', '>Galerie</a>'),
 ('<h4>Contact</h4>', '<h4>Contact</h4>'),
 ('>Get in Touch</a>', '>Nous contacter</a>'),
 ('>Live Chat on WhatsApp</a>', '>Chat en direct sur WhatsApp</a>'),
 ('>Email Us</a>', '>Nous écrire</a>'),
 ('<h4>Purpose</h4>', '<h4>Notre mission</h4>'),
 ('>Responsible Travel</a>', '>Voyage responsable</a>'),
 ('>Community Journey</a>', '>Voyage communautaire</a>'),
 ('>Traveller Reviews</a>', '>Avis des voyageurs</a>'),
 ('>Leave a Google Review</a>', '>Laisser un avis Google</a>'),
 ('All rights reserved.', 'Tous droits réservés.'),
 ('>Terms</a>', '>Conditions</a>'),
 ('>Privacy</a>', '>Confidentialité</a>'),
 ('>Made in Morocco</span>', '>Fait au Maroc</span>'),
 ('aria-label="Subscribe"', 'aria-label="S\u2019abonner"'),
 ('aria-label="Close">✕</button>', 'aria-label="Fermer">✕</button>'),
 ('Morocco in your inbox', 'Le Maroc dans votre boîte mail'),
 ('One short letter a month — routes, seasons, secret spots. No spam, ever.', 'Une courte lettre par mois — itinéraires, saisons, adresses secrètes. Jamais de spam.'),
 ('<label for="abridName">Your name</label>', '<label for="abridName">Votre nom</label>'),
 ('<label for="abridEmail">Email address</label>', '<label for="abridEmail">Adresse e-mail</label>'),
 ("I'm dreaming of…", 'Je rêve de…'),
 ('>Anywhere in Morocco</option>', '>Partout au Maroc</option>'),
 ('>Sahara desert</option>', '>Désert du Sahara</option>'),
 ('>High Atlas</option>', '>Haut Atlas</option>'),
 ('>Imperial cities</option>', '>Cités impériales</option>'),
 ('>Subscribe free</button>', '>S\u2019abonner gratuitement</button>'),
 ('Unsubscribe anytime with one click.', 'Désinscription en un clic à tout moment.'),
]

NAV_FR = [
 ('<li><a href="https://www.abridmorocco.com/index.html">Home</a></li>', '<li><a href="https://www.abridmorocco.com/index.html">Accueil</a></li>'),
 ('<li><a href="https://www.abridmorocco.com/trips.html">Trips</a></li>', '<li><a href="https://www.abridmorocco.com/trips.html">Circuits</a></li>'),
 ('<li><a href="https://www.abridmorocco.com/experiences.html">Experiences</a></li>', '<li><a href="https://www.abridmorocco.com/experiences.html">Expériences</a></li>'),
 ('<li><a href="https://www.abridmorocco.com/blog.html">Morocco Guide</a></li>', '<li><a href="https://www.abridmorocco.com/blog.html">Guide du Maroc</a></li>'),
 ('class="nav-cta">Plan My Trip</a>', 'class="nav-cta">Planifier mon voyage</a>'),
 ('<li><a href="https://www.abridmorocco.com/about.html">About</a></li>', '<li><a href="https://www.abridmorocco.com/about.html">À propos</a></li>'),
 ('<a href="https://www.abridmorocco.com/index.html">Home</a>', '<a href="https://www.abridmorocco.com/index.html">Accueil</a>'),
 ('<a href="https://www.abridmorocco.com/trips.html">Trips</a>', '<a href="https://www.abridmorocco.com/trips.html">Circuits</a>'),
 ('<a href="https://www.abridmorocco.com/destinations.html">Destinations</a>', '<a href="https://www.abridmorocco.com/destinations.html">Destinations</a>'),
 ('<a href="https://www.abridmorocco.com/experiences.html">Experiences</a>', '<a href="https://www.abridmorocco.com/experiences.html">Expériences</a>'),
 ('<a href="https://www.abridmorocco.com/blog.html">Morocco Guide</a>', '<a href="https://www.abridmorocco.com/blog.html">Guide du Maroc</a>'),
 ('<a href="https://www.abridmorocco.com/plan-my-trip.html">Plan My Trip</a>', '<a href="https://www.abridmorocco.com/plan-my-trip.html">Planifier mon voyage</a>'),
 ('<a href="https://www.abridmorocco.com/about.html">About Abrid</a>', '<a href="https://www.abridmorocco.com/about.html">À propos d\u2019Abrid</a>'),
 ('<a href="https://www.abridmorocco.com/contact.html">Contact</a>', '<a href="https://www.abridmorocco.com/contact.html">Contact</a>'),
]

COMMON_ES = [
 ("Abrid Morocco home", "Inicio de Abrid Morocco"),
 ("Search Abrid Morocco", "Buscar en Abrid Morocco"),
 ("Chat with Abrid Morocco on WhatsApp", "Chatear con Abrid Morocco por WhatsApp"),
 ("Chat with Abrid on WhatsApp", "Chatear con Abrid por WhatsApp"),
 ('aria-label="Reserve a tour"', 'aria-label="Reservar un tour"'),
 ('aria-label="Open menu"', 'aria-label="Abrir el menú"'),
 ("PREMIUM TOURS", "TOURS PREMIUM"),
 ("Morocco travel platform", "Plataforma de viajes por Marruecos"),
 ("Imperial Cities - private guides", "Ciudades Imperiales: guías privados"),
 ("Imperial Cities — private guides", "Ciudades Imperiales: guías privados"),
 ("characterful stays since 2022.", "alojamientos con encanto desde 2022."),
 ("Skip to main content", "Ir al contenido principal"),
 ('>Search</a>', '>Buscar</a>'),
 ('>Reserve</button>', '>Reservar</button>'),
 ('placeholder="Search trips, destinations, guides..."', 'placeholder="Buscar viajes, destinos, guías..."'),
 ('placeholder="Search trips, destinations, guides…"', 'placeholder="Buscar viajes, destinos, guías…"'),
 ('aria-label="Search">', 'aria-label="Búsqueda">'),
 ('>Close</button>', '>Cerrar</button>'),
 ('aria-label="Cookie consent"', 'aria-label="Consentimiento de cookies"'),
 ('cookie policy</a>', 'política de cookies</a>'),
 ('We use cookies to improve your experience and analyse site traffic. Read our', 'Usamos cookies para mejorar tu experiencia y analizar el tráfico del sitio. Lee nuestra'),
 ('>Accept</button>', '>Aceptar</button>'),
 ('>Decline</button>', '>Rechazar</button>'),
 ('<h4>Booking</h4>', '<h4>Reserva</h4>'),
 ('>How Booking Works</a>', '>Cómo funciona la reserva</a>'),
 ('>Cancellation Policy</a>', '>Política de cancelación</a>'),
 ('>Terms of Service</a>', '>Términos del servicio</a>'),
 ('>Airport Transfer</a>', '>Traslado al aeropuerto</a>'),
 ('<h4>Company</h4>', '<h4>Empresa</h4>'),
 ('>About Us</a>', '>Quiénes somos</a>'),
 ('>Gallery</a>', '>Galería</a>'),
 ('<h4>Contact</h4>', '<h4>Contacto</h4>'),
 ('>Get in Touch</a>', '>Contáctanos</a>'),
 ('>Live Chat on WhatsApp</a>', '>Chat en vivo por WhatsApp</a>'),
 ('>FAQ</a>', '>Preguntas frecuentes</a>'),
 ('>Email Us</a>', '>Escríbenos</a>'),
 ('<h4>Purpose</h4>', '<h4>Nuestro propósito</h4>'),
 ('>Responsible Travel</a>', '>Viaje responsable</a>'),
 ('>Community Journey</a>', '>Viaje comunitario</a>'),
 ('>Traveller Reviews</a>', '>Opiniones de viajeros</a>'),
 ('>Leave a Google Review</a>', '>Dejar una reseña en Google</a>'),
 ('All rights reserved.', 'Todos los derechos reservados.'),
 ('>Terms</a>', '>Términos</a>'),
 ('>Privacy</a>', '>Privacidad</a>'),
 ('>Made in Morocco</span>', '>Hecho en Marruecos</span>'),
 ('aria-label="Subscribe"', 'aria-label="Suscribirse"'),
 ('aria-label="Close">✕</button>', 'aria-label="Cerrar">✕</button>'),
 ('Morocco in your inbox', 'Marruecos en tu correo'),
 ('One short letter a month — routes, seasons, secret spots. No spam, ever.', 'Una carta breve al mes: rutas, estaciones, rincones secretos. Nada de spam.'),
 ('<label for="abridName">Your name</label>', '<label for="abridName">Tu nombre</label>'),
 ('<label for="abridEmail">Email address</label>', '<label for="abridEmail">Correo electrónico</label>'),
 ("I'm dreaming of…", 'Sueño con…'),
 ('>Anywhere in Morocco</option>', '>Cualquier lugar de Marruecos</option>'),
 ('>Sahara desert</option>', '>Desierto del Sáhara</option>'),
 ('>High Atlas</option>', '>Alto Atlas</option>'),
 ('>Imperial cities</option>', '>Ciudades imperiales</option>'),
 ('>Subscribe free</button>', '>Suscribirme gratis</button>'),
 ('Unsubscribe anytime with one click.', 'Date de baja en un clic cuando quieras.'),
]

NAV_ES = [
 ('<li><a href="https://www.abridmorocco.com/index.html">Home</a></li>', '<li><a href="https://www.abridmorocco.com/index.html">Inicio</a></li>'),
 ('<li><a href="https://www.abridmorocco.com/trips.html">Trips</a></li>', '<li><a href="https://www.abridmorocco.com/trips.html">Viajes</a></li>'),
 ('<li><a href="https://www.abridmorocco.com/destinations.html">Destinations</a></li>', '<li><a href="https://www.abridmorocco.com/destinations.html">Destinos</a></li>'),
 ('<li><a href="https://www.abridmorocco.com/experiences.html">Experiences</a></li>', '<li><a href="https://www.abridmorocco.com/experiences.html">Experiencias</a></li>'),
 ('<li><a href="https://www.abridmorocco.com/blog.html">Morocco Guide</a></li>', '<li><a href="https://www.abridmorocco.com/blog.html">Guía de Marruecos</a></li>'),
 ('class="nav-cta">Plan My Trip</a>', 'class="nav-cta">Planifica mi viaje</a>'),
 ('<li><a href="https://www.abridmorocco.com/about.html">About</a></li>', '<li><a href="https://www.abridmorocco.com/about.html">Nosotros</a></li>'),
 ('<li><a href="https://www.abridmorocco.com/contact.html">Contact</a></li>', '<li><a href="https://www.abridmorocco.com/contact.html">Contacto</a></li>'),
 ('<a href="https://www.abridmorocco.com/index.html">Home</a>', '<a href="https://www.abridmorocco.com/index.html">Inicio</a>'),
 ('<a href="https://www.abridmorocco.com/trips.html">Trips</a>', '<a href="https://www.abridmorocco.com/trips.html">Viajes</a>'),
 ('<a href="https://www.abridmorocco.com/destinations.html">Destinations</a>', '<a href="https://www.abridmorocco.com/destinations.html">Destinos</a>'),
 ('<a href="https://www.abridmorocco.com/experiences.html">Experiences</a>', '<a href="https://www.abridmorocco.com/experiences.html">Experiencias</a>'),
 ('<a href="https://www.abridmorocco.com/blog.html">Morocco Guide</a>', '<a href="https://www.abridmorocco.com/blog.html">Guía de Marruecos</a>'),
 ('<a href="https://www.abridmorocco.com/plan-my-trip.html">Plan My Trip</a>', '<a href="https://www.abridmorocco.com/plan-my-trip.html">Planifica mi viaje</a>'),
 ('<a href="https://www.abridmorocco.com/about.html">About Abrid</a>', '<a href="https://www.abridmorocco.com/about.html">Sobre Abrid</a>'),
 ('<a href="https://www.abridmorocco.com/contact.html">Contact</a>', '<a href="https://www.abridmorocco.com/contact.html">Contacto</a>'),
]

print("common loaded")
